# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

import hashlib
import importlib.util
import json
import os
import stat
import sys
from collections.abc import Callable, Mapping
from pathlib import Path
from types import ModuleType
from typing import Any

import pytest

ROOT = Path(__file__).resolve().parents[2]
MODULE_PATH = ROOT / "scripts/telemetry_generated_transaction.py"
JSON_MARKER = b'"x-defenseclaw-generated"'
GO_MARKER = b"Code generated by DefenseClaw telemetry registry; DO NOT EDIT."


def _load_module(name: str = "telemetry_generated_transaction_test") -> ModuleType:
    spec = importlib.util.spec_from_file_location(name, MODULE_PATH)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture
def transaction() -> ModuleType:
    return _load_module()


@pytest.fixture
def repository(tmp_path: Path) -> Path:
    root = tmp_path / "repository"
    (root / ".git").mkdir(parents=True)
    (root / "schemas/telemetry/generated").mkdir(parents=True)
    (root / "internal/observability").mkdir(parents=True)
    return root


def _json_payload(version: int, role: str) -> bytes:
    return (
        '{\n  "x-defenseclaw-generated": {"generator": "telemetry-registry"},\n'
        f'  "role": "{role}",\n  "version": {version}\n}}\n'
    ).encode()


def _outputs(transaction: ModuleType, version: int, *, include_extra: bool = True) -> dict[str, Any]:
    rendered = transaction.RenderedOutput
    outputs = {
        transaction.MANIFEST_PATH: rendered(_json_payload(version, "manifest"), JSON_MARKER),
        "schemas/telemetry/generated/catalog.json": rendered(
            _json_payload(version, "catalog"),
            JSON_MARKER,
        ),
    }
    for index, path in enumerate(sorted(transaction.EXACT_INTERNAL_OUTPUTS)):
        outputs[path] = rendered(
            (
                "// Code generated by DefenseClaw telemetry registry; DO NOT EDIT.\n"
                f"package observability\n\nconst generatedVersion{index} = {version}\n"
            ).encode(),
            GO_MARKER,
        )
    if include_extra:
        outputs["schemas/telemetry/generated/otlp-fixtures/cases/case.json"] = rendered(
            _json_payload(version, "case"),
            JSON_MARKER,
        )
    return outputs


def _ownership(transaction: ModuleType, outputs: Mapping[str, Any]) -> dict[str, Any]:
    return {path: transaction.PriorOwnedOutput.from_rendered(output) for path, output in outputs.items()}


def _adoption_outputs(transaction: ModuleType, version: int) -> dict[str, Any]:
    outputs = _outputs(transaction, version, include_extra=False)
    for index, path in enumerate(sorted(transaction.EXACT_BASELINE_ADOPTION_PATHS)):
        outputs[path] = transaction.RenderedOutput(
            _json_payload(version, f"adopted-{index}"),
            JSON_MARKER,
        )
    return outputs


def _install_adoption_predecessors(
    transaction: ModuleType,
    repository: Path,
) -> tuple[dict[str, Any], dict[str, tuple[bytes, int]]]:
    adoption: dict[str, Any] = {}
    predecessors: dict[str, tuple[bytes, int]] = {}
    for index, path in enumerate(sorted(transaction.EXACT_BASELINE_ADOPTION_PATHS)):
        payload = (
            json.dumps(
                {"legacy": True, "ordinal": index, "path": path},
                sort_keys=True,
                separators=(",", ":"),
            )
            + "\n"
        ).encode()
        target = repository / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(payload)
        target.chmod(0o644)
        adoption[path] = transaction.BaselineAdoption(
            payload=payload,
            sha256=hashlib.sha256(payload).hexdigest(),
            absent_marker=JSON_MARKER,
        )
        predecessors[path] = (payload, 0o644)
    return adoption, predecessors


def _continued_adoption_authority(transaction: ModuleType) -> dict[str, Any]:
    return {path: transaction.ContinuedAdoptionAuthority() for path in transaction.EXACT_BASELINE_ADOPTION_PATHS}


def _assert_adoption_predecessors(
    repository: Path,
    predecessors: Mapping[str, tuple[bytes, int]],
) -> None:
    for path, (payload, mode) in predecessors.items():
        target = repository / path
        assert target.read_bytes() == payload
        assert stat.S_IMODE(target.stat().st_mode) == mode


def _worktree_snapshot(root: Path) -> dict[str, tuple[bytes, int]]:
    result: dict[str, tuple[bytes, int]] = {}
    for base in (root / "schemas", root / "internal"):
        for path in base.rglob("*"):
            if path.is_file() and not path.is_symlink():
                result[path.relative_to(root).as_posix()] = (
                    path.read_bytes(),
                    stat.S_IMODE(path.stat().st_mode),
                )
    return result


def _assert_outputs(root: Path, outputs: Mapping[str, Any]) -> None:
    for path, output in outputs.items():
        target = root / path
        assert target.read_bytes() == output.payload
        assert stat.S_IMODE(target.stat().st_mode) == output.mode


def _worktree_repository(tmp_path: Path) -> Path:
    root = tmp_path / "linked-worktree"
    (root / "schemas/telemetry/generated").mkdir(parents=True)
    (root / "internal/observability").mkdir(parents=True)
    return root


def test_baseline_adoption_uses_the_exact_reviewed_26_path_authority_and_then_normal_ownership(
    transaction: ModuleType,
    repository: Path,
) -> None:
    assert len(transaction.EXACT_BASELINE_ADOPTION_PATHS) == 26
    adoption, _predecessors = _install_adoption_predecessors(transaction, repository)
    first = _adoption_outputs(transaction, 1)

    transaction.write_outputs(repository, first, {}, adoption=adoption)
    _assert_outputs(repository, first)
    continued = _continued_adoption_authority(transaction)
    transaction.check_outputs(repository, first, _ownership(transaction, first), adoption=continued)

    second = _adoption_outputs(transaction, 2)
    transaction.write_outputs(
        repository,
        second,
        _ownership(transaction, first),
        adoption=continued,
    )
    _assert_outputs(repository, second)
    transaction.check_outputs(repository, second, _ownership(transaction, second), adoption=continued)

    continued_evidence = next(iter(continued.values()))
    assert continued_evidence.__slots__ == ()
    assert not hasattr(continued_evidence, "payload")
    assert not hasattr(continued_evidence, "sha256")
    with pytest.raises(TypeError):
        transaction.ContinuedAdoptionAuthority(b"legacy bytes")


def test_baseline_adoption_rejects_wrong_same_count_path_substitution_before_writes(
    transaction: ModuleType,
    repository: Path,
) -> None:
    adoption, _predecessors = _install_adoption_predecessors(transaction, repository)
    before = _worktree_snapshot(repository)
    removed = sorted(adoption)[0]
    replacement = "schemas/not-a-reviewed-public-schema.json"
    substituted = dict(adoption)
    substituted[replacement] = substituted.pop(removed)

    with pytest.raises(transaction.TransactionError, match="outside the exact reviewed allowlist"):
        transaction.write_outputs(
            repository,
            _adoption_outputs(transaction, 1),
            {},
            adoption=substituted,
        )

    assert _worktree_snapshot(repository) == before


def test_baseline_adoption_rejects_partial_or_disappearing_authority(
    transaction: ModuleType,
    repository: Path,
) -> None:
    adoption, _predecessors = _install_adoption_predecessors(transaction, repository)
    outputs = _adoption_outputs(transaction, 1)
    omitted = sorted(adoption)[0]

    partial = dict(adoption)
    partial.pop(omitted)
    with pytest.raises(transaction.TransactionError, match="exact 26-path set"):
        transaction.write_outputs(repository, outputs, {}, adoption=partial)

    missing_desired = dict(outputs)
    missing_desired.pop(omitted)
    with pytest.raises(transaction.TransactionError, match="authority cannot disappear"):
        transaction.write_outputs(repository, missing_desired, {}, adoption=adoption)

    transaction.write_outputs(repository, outputs, {}, adoption=adoption)
    partial_prior = {omitted: _ownership(transaction, outputs)[omitted]}
    with pytest.raises(transaction.TransactionError, match="zero adoption paths"):
        transaction.write_outputs(repository, outputs, partial_prior, adoption=adoption)
    continued = _continued_adoption_authority(transaction)
    with pytest.raises(transaction.TransactionError, match="all adoption paths"):
        transaction.write_outputs(repository, outputs, partial_prior, adoption=continued)
    missing_repeat_desired = dict(outputs)
    missing_repeat_desired.pop(omitted)
    with pytest.raises(transaction.TransactionError, match="authority cannot disappear"):
        transaction.write_outputs(
            repository,
            missing_repeat_desired,
            _ownership(transaction, outputs),
            adoption=continued,
        )
    with pytest.raises(transaction.TransactionError, match="outside the allowlist"):
        transaction.write_outputs(repository, outputs, _ownership(transaction, outputs))


def test_adoption_modes_reject_mixed_or_wrong_phase_evidence_before_writes(
    transaction: ModuleType,
    repository: Path,
) -> None:
    baseline, _predecessors = _install_adoption_predecessors(transaction, repository)
    outputs = _adoption_outputs(transaction, 1)
    before = _worktree_snapshot(repository)
    continued = _continued_adoption_authority(transaction)
    mixed = dict(baseline)
    mixed[sorted(mixed)[0]] = transaction.ContinuedAdoptionAuthority()

    with pytest.raises(transaction.TransactionError, match="cannot mix baseline and continued"):
        transaction.write_outputs(repository, outputs, {}, adoption=mixed)
    with pytest.raises(transaction.TransactionError, match="all adoption paths"):
        transaction.write_outputs(repository, outputs, {}, adoption=continued)
    assert _worktree_snapshot(repository) == before

    transaction.write_outputs(repository, outputs, {}, adoption=baseline)
    generated = _worktree_snapshot(repository)
    with pytest.raises(transaction.TransactionError, match="zero adoption paths"):
        transaction.write_outputs(
            repository,
            _adoption_outputs(transaction, 2),
            _ownership(transaction, outputs),
            adoption=baseline,
        )
    assert _worktree_snapshot(repository) == generated


@pytest.mark.parametrize("mutation", ["bytes", "mode", "symlink", "hardlink"])
def test_baseline_adoption_authenticates_each_regular_single_link_predecessor(
    transaction: ModuleType,
    repository: Path,
    mutation: str,
) -> None:
    adoption, _predecessors = _install_adoption_predecessors(transaction, repository)
    path = sorted(adoption)[0]
    target = repository / path
    if mutation == "bytes":
        target.write_bytes(b"changed legacy bytes\n")
    elif mutation == "mode":
        target.chmod(0o600)
    elif mutation == "symlink":
        target.unlink()
        outside = repository.parent / "adoption-outside"
        outside.write_bytes(adoption[path].payload)
        target.symlink_to(outside)
    else:
        outside = repository.parent / "adoption-hardlink"
        outside.write_bytes(adoption[path].payload)
        target.unlink()
        os.link(outside, target)

    before = _worktree_snapshot(repository)
    with pytest.raises(transaction.TransactionError):
        transaction.write_outputs(
            repository,
            _adoption_outputs(transaction, 1),
            {},
            adoption=adoption,
        )
    assert _worktree_snapshot(repository) == before


def test_baseline_adoption_rejects_unauthenticated_digest_and_marker_binding(
    transaction: ModuleType,
    repository: Path,
) -> None:
    adoption, _predecessors = _install_adoption_predecessors(transaction, repository)
    path = sorted(adoption)[0]
    predecessor = adoption[path]

    wrong_digest = dict(adoption)
    wrong_digest[path] = transaction.BaselineAdoption(
        predecessor.payload,
        "0" * 64,
        predecessor.absent_marker,
        predecessor.mode,
    )
    with pytest.raises(transaction.TransactionError, match="bytes disagree with their digest"):
        transaction.write_outputs(
            repository,
            _adoption_outputs(transaction, 1),
            {},
            adoption=wrong_digest,
        )

    wrong_marker = dict(adoption)
    wrong_marker[path] = transaction.BaselineAdoption(
        predecessor.payload,
        predecessor.sha256,
        b"different-future-marker",
        predecessor.mode,
    )
    with pytest.raises(transaction.TransactionError, match="absent marker disagrees"):
        transaction.write_outputs(
            repository,
            _adoption_outputs(transaction, 1),
            {},
            adoption=wrong_marker,
        )

    marked_payload = predecessor.payload + JSON_MARKER + b"\n"
    marker_present = dict(adoption)
    marker_present[path] = transaction.BaselineAdoption(
        marked_payload,
        hashlib.sha256(marked_payload).hexdigest(),
        JSON_MARKER,
        predecessor.mode,
    )
    with pytest.raises(transaction.TransactionError, match="already carries generated authority"):
        transaction.write_outputs(
            repository,
            _adoption_outputs(transaction, 1),
            {},
            adoption=marker_present,
        )


@pytest.mark.parametrize(
    ("failure_stage", "failure_path"),
    [
        ("stage_created", None),
        ("output_staged", None),
        ("staging_fsynced", None),
        ("output_backed_up", None),
        ("backups_complete", None),
        ("transaction_ancestors_fsynced", None),
        ("journal_published", "prepared"),
        ("journal_prepared", None),
        ("target_directories_created", None),
        ("before_output_apply", None),
        ("after_output_apply", None),
        ("before_manifest_apply", None),
        ("after_manifest_apply", None),
    ],
)
def test_baseline_adoption_precommit_faults_restore_every_predecessor(
    transaction: ModuleType,
    repository: Path,
    failure_stage: str,
    failure_path: str | None,
) -> None:
    adoption, predecessors = _install_adoption_predecessors(transaction, repository)
    failed = False

    def fail(stage: str, path: str | None) -> None:
        nonlocal failed
        if not failed and stage == failure_stage and (failure_path is None or path == failure_path):
            failed = True
            raise RuntimeError("adoption fault")

    with pytest.raises(transaction.TransactionError):
        transaction.write_outputs(
            repository,
            _adoption_outputs(transaction, 1),
            {},
            adoption=adoption,
            fault_injector=fail,
        )

    assert failed
    _assert_adoption_predecessors(repository, predecessors)
    assert not (repository / transaction.MANIFEST_PATH).exists()


def test_baseline_adoption_interruption_recovers_all_predecessors(
    transaction: ModuleType,
    repository: Path,
) -> None:
    adoption, predecessors = _install_adoption_predecessors(transaction, repository)

    class Crash(BaseException):
        pass

    def crash(stage: str, path: str | None) -> None:
        if stage == "after_output_apply" and path in adoption:
            raise Crash

    with pytest.raises(Crash):
        transaction.write_outputs(
            repository,
            _adoption_outputs(transaction, 1),
            {},
            adoption=adoption,
            fault_injector=crash,
        )

    assert transaction.recover_outputs(repository) == transaction.RecoveryResult(True, "rolled_back")
    _assert_adoption_predecessors(repository, predecessors)
    assert not (repository / transaction.MANIFEST_PATH).exists()


def test_continued_adoption_interruption_uses_v2_normal_prior_rollback(
    transaction: ModuleType,
    repository: Path,
) -> None:
    adoption, _predecessors = _install_adoption_predecessors(transaction, repository)
    first = _adoption_outputs(transaction, 1)
    second = _adoption_outputs(transaction, 2)
    transaction.write_outputs(repository, first, {}, adoption=adoption)

    class Crash(BaseException):
        pass

    def crash(stage: str, path: str | None) -> None:
        if stage == "after_output_apply" and path in transaction.EXACT_BASELINE_ADOPTION_PATHS:
            raise Crash

    with pytest.raises(Crash):
        transaction.write_outputs(
            repository,
            second,
            _ownership(transaction, first),
            adoption=_continued_adoption_authority(transaction),
            fault_injector=crash,
        )

    state = repository / transaction.STATE_DIRECTORY.as_posix()
    journal = transaction._read_journal(state)
    assert journal is not None and journal.format_version == 2 and journal.phase == "prepared"
    adopted = [item for item in journal.prior if item.adopted]
    assert len(adopted) == 26
    assert all(item.marker == JSON_MARKER and item.absent_marker is None for item in adopted)
    assert transaction.recover_outputs(repository) == transaction.RecoveryResult(True, "rolled_back")
    _assert_outputs(repository, first)


def test_baseline_adoption_committed_interruption_completes_without_restoring_predecessors(
    transaction: ModuleType,
    repository: Path,
) -> None:
    adoption, _predecessors = _install_adoption_predecessors(transaction, repository)
    outputs = _adoption_outputs(transaction, 1)

    class Crash(BaseException):
        pass

    def crash(stage: str, _path: str | None) -> None:
        if stage == "journal_committed":
            raise Crash

    with pytest.raises(Crash):
        transaction.write_outputs(
            repository,
            outputs,
            {},
            adoption=adoption,
            fault_injector=crash,
        )

    assert transaction.recover_outputs(repository) == transaction.RecoveryResult(True, "completed")
    _assert_outputs(repository, outputs)


def test_continued_adoption_committed_interruption_completes_new_outputs(
    transaction: ModuleType,
    repository: Path,
) -> None:
    adoption, _predecessors = _install_adoption_predecessors(transaction, repository)
    first = _adoption_outputs(transaction, 1)
    second = _adoption_outputs(transaction, 2)
    transaction.write_outputs(repository, first, {}, adoption=adoption)

    class Crash(BaseException):
        pass

    def crash(stage: str, _path: str | None) -> None:
        if stage == "journal_committed":
            raise Crash

    with pytest.raises(Crash):
        transaction.write_outputs(
            repository,
            second,
            _ownership(transaction, first),
            adoption=_continued_adoption_authority(transaction),
            fault_injector=crash,
        )

    state = repository / transaction.STATE_DIRECTORY.as_posix()
    journal = transaction._read_journal(state)
    assert journal is not None and journal.format_version == 2 and journal.phase == "committed"
    adopted = [item for item in journal.prior if item.adopted]
    assert len(adopted) == 26
    assert all(item.marker == JSON_MARKER and item.absent_marker is None for item in adopted)
    assert transaction.recover_outputs(repository) == transaction.RecoveryResult(True, "completed")
    _assert_outputs(repository, second)


def test_baseline_adoption_lock_contention_never_touches_predecessors(
    transaction: ModuleType,
    repository: Path,
) -> None:
    adoption, predecessors = _install_adoption_predecessors(transaction, repository)
    state = transaction._state_root(repository, create=True)

    with transaction._exclusive_lock(state):
        with pytest.raises(transaction.TransactionBusyError):
            transaction.write_outputs(
                repository,
                _adoption_outputs(transaction, 1),
                {},
                adoption=adoption,
            )

    _assert_adoption_predecessors(repository, predecessors)


def test_baseline_adoption_concurrent_predecessor_change_is_never_overwritten(
    transaction: ModuleType,
    repository: Path,
) -> None:
    adoption, _predecessors = _install_adoption_predecessors(transaction, repository)
    path = sorted(adoption)[0]
    manual = b"concurrent operator content\n"
    changed = False

    def change_before_apply(stage: str, candidate: str | None) -> None:
        nonlocal changed
        if stage == "before_output_apply" and candidate == path and not changed:
            (repository / path).write_bytes(manual)
            changed = True

    with pytest.raises(transaction.RollbackError, match="rollback both failed"):
        transaction.write_outputs(
            repository,
            _adoption_outputs(transaction, 1),
            {},
            adoption=adoption,
            fault_injector=change_before_apply,
        )

    assert changed
    assert (repository / path).read_bytes() == manual


def test_recovery_accepts_pre_adoption_v1_journal_format(
    transaction: ModuleType,
    repository: Path,
) -> None:
    first = _outputs(transaction, 1, include_extra=False)
    transaction.write_outputs(repository, first, {})

    class Crash(BaseException):
        pass

    def crash(stage: str, _path: str | None) -> None:
        if stage == "journal_prepared":
            raise Crash

    with pytest.raises(Crash):
        transaction.write_outputs(
            repository,
            _outputs(transaction, 2, include_extra=False),
            _ownership(transaction, first),
            fault_injector=crash,
        )

    state = repository / transaction.STATE_DIRECTORY.as_posix()
    journal_path = state / transaction.JOURNAL_NAME
    journal = json.loads(journal_path.read_bytes())
    journal["format_version"] = 1
    for prior in journal["prior"]:
        prior.pop("adopted")
        prior.pop("absent_marker")
    journal_path.write_bytes(transaction._canonical_json(journal))

    assert transaction.recover_outputs(repository) == transaction.RecoveryResult(True, "rolled_back")
    _assert_outputs(repository, first)


def test_recovery_completes_pre_adoption_committed_v1_journal_format(
    transaction: ModuleType,
    repository: Path,
) -> None:
    first = _outputs(transaction, 1, include_extra=False)
    second = _outputs(transaction, 2, include_extra=False)
    transaction.write_outputs(repository, first, {})

    class Crash(BaseException):
        pass

    def crash(stage: str, _path: str | None) -> None:
        if stage == "journal_committed":
            raise Crash

    with pytest.raises(Crash):
        transaction.write_outputs(
            repository,
            second,
            _ownership(transaction, first),
            fault_injector=crash,
        )

    state = repository / transaction.STATE_DIRECTORY.as_posix()
    journal_path = state / transaction.JOURNAL_NAME
    journal = json.loads(journal_path.read_bytes())
    assert journal["phase"] == "committed"
    journal["format_version"] = 1
    for prior in journal["prior"]:
        prior.pop("adopted")
        prior.pop("absent_marker")
    journal_path.write_bytes(transaction._canonical_json(journal))

    assert transaction.recover_outputs(repository) == transaction.RecoveryResult(True, "completed")
    _assert_outputs(repository, second)


def test_recovery_rejects_partial_v2_adoption_authority(
    transaction: ModuleType,
    repository: Path,
) -> None:
    adoption, _predecessors = _install_adoption_predecessors(transaction, repository)

    class Crash(BaseException):
        pass

    def crash(stage: str, _path: str | None) -> None:
        if stage == "journal_prepared":
            raise Crash

    with pytest.raises(Crash):
        transaction.write_outputs(
            repository,
            _adoption_outputs(transaction, 1),
            {},
            adoption=adoption,
            fault_injector=crash,
        )

    state = repository / transaction.STATE_DIRECTORY.as_posix()
    journal_path = state / transaction.JOURNAL_NAME
    journal = json.loads(journal_path.read_bytes())
    removed_path = sorted(transaction.EXACT_BASELINE_ADOPTION_PATHS)[-1]
    journal["prior"] = [item for item in journal["prior"] if item["path"] != removed_path]
    journal["desired"] = [item for item in journal["desired"] if item["path"] != removed_path]
    for index, item in enumerate(journal["prior"]):
        parent = Path(item["path"]).parent.as_posix()
        item["apply_detached"] = f"{parent}/.defenseclaw-telemetry-{journal['token']}-{index:06d}-apply"
        item["rollback_detached"] = f"{parent}/.defenseclaw-telemetry-{journal['token']}-{index:06d}-rollback"
        item["retired"] = f"retired/{index:06d}.retired"
        item["discard_apply"] = f"discard/{index:06d}.apply"
        item["discard_rollback"] = f"discard/{index:06d}.rollback"
    journal_path.write_bytes(transaction._canonical_json(journal))

    with pytest.raises(transaction.RecoveryRequiredError, match="adoption authority is incomplete"):
        transaction.recover_outputs(repository)


def test_recovery_rejects_repeat_owned_v2_adoption_missing_from_desired_set(
    transaction: ModuleType,
    repository: Path,
) -> None:
    adoption, _predecessors = _install_adoption_predecessors(transaction, repository)
    first = _adoption_outputs(transaction, 1)
    transaction.write_outputs(repository, first, {}, adoption=adoption)
    continued = _continued_adoption_authority(transaction)

    class Crash(BaseException):
        pass

    def crash(stage: str, _path: str | None) -> None:
        if stage == "journal_prepared":
            raise Crash

    with pytest.raises(Crash):
        transaction.write_outputs(
            repository,
            _adoption_outputs(transaction, 2),
            _ownership(transaction, first),
            adoption=continued,
            fault_injector=crash,
        )

    state = repository / transaction.STATE_DIRECTORY.as_posix()
    journal_path = state / transaction.JOURNAL_NAME
    journal = json.loads(journal_path.read_bytes())
    adopted_prior = [item for item in journal["prior"] if item["adopted"]]
    assert len(adopted_prior) == 26
    assert all(item["marker"] is not None and item["absent_marker"] is None for item in adopted_prior)
    removed_path = sorted(transaction.EXACT_BASELINE_ADOPTION_PATHS)[0]
    journal["desired"] = [item for item in journal["desired"] if item["path"] != removed_path]
    journal_path.write_bytes(transaction._canonical_json(journal))

    with pytest.raises(transaction.RecoveryRequiredError, match="adoption desired set is incomplete"):
        transaction.recover_outputs(repository)


@pytest.mark.parametrize("source_mode", ["baseline", "continued"])
def test_recovery_rejects_mixed_v2_adoption_modes(
    transaction: ModuleType,
    repository: Path,
    source_mode: str,
) -> None:
    adoption, _predecessors = _install_adoption_predecessors(transaction, repository)
    first = _adoption_outputs(transaction, 1)
    if source_mode == "continued":
        transaction.write_outputs(repository, first, {}, adoption=adoption)
        outputs = _adoption_outputs(transaction, 2)
        prior_owned = _ownership(transaction, first)
        authority = _continued_adoption_authority(transaction)
    else:
        outputs = first
        prior_owned = {}
        authority = adoption

    class Crash(BaseException):
        pass

    def crash(stage: str, _path: str | None) -> None:
        if stage == "journal_prepared":
            raise Crash

    with pytest.raises(Crash):
        transaction.write_outputs(
            repository,
            outputs,
            prior_owned,
            adoption=authority,
            fault_injector=crash,
        )

    state = repository / transaction.STATE_DIRECTORY.as_posix()
    journal_path = state / transaction.JOURNAL_NAME
    journal = json.loads(journal_path.read_bytes())
    adopted_prior = [item for item in journal["prior"] if item["adopted"]]
    assert len(adopted_prior) == 26
    mutated = adopted_prior[0]
    if source_mode == "baseline":
        assert mutated["marker"] is None and mutated["absent_marker"] is not None
        mutated["marker"] = transaction._marker_text(JSON_MARKER)
        mutated["absent_marker"] = None
    else:
        assert mutated["marker"] is not None and mutated["absent_marker"] is None
        mutated["marker"] = None
        mutated["absent_marker"] = transaction._marker_text(JSON_MARKER)
    journal_path.write_bytes(transaction._canonical_json(journal))

    with pytest.raises(transaction.RecoveryRequiredError, match="adoption mode is mixed"):
        transaction.recover_outputs(repository)


def test_write_check_update_and_delete_are_deterministic_and_manifest_last(
    transaction: ModuleType,
    repository: Path,
) -> None:
    first = _outputs(transaction, 1)
    order: list[tuple[str, str | None]] = []
    result = transaction.write_outputs(
        repository,
        first,
        {},
        fault_injector=lambda stage, path: order.append((stage, path)),
    )
    assert result == transaction.RecoveryResult(False, "written")
    _assert_outputs(repository, first)
    transaction.check_outputs(repository, first, _ownership(transaction, first))
    manifest_index = order.index(("after_manifest_apply", transaction.MANIFEST_PATH))
    assert all(
        index < manifest_index
        for index, item in enumerate(order)
        if item[0] in {"after_output_apply", "after_output_delete"}
    )

    second = _outputs(transaction, 2, include_extra=False)
    result = transaction.write_outputs(repository, second, _ownership(transaction, first))
    assert result == transaction.RecoveryResult(False, "written")
    _assert_outputs(repository, second)
    assert not (repository / "schemas/telemetry/generated/otlp-fixtures/cases/case.json").exists()
    transaction.check_outputs(repository, second, _ownership(transaction, second))

    before = _worktree_snapshot(repository)
    transaction.write_outputs(repository, second, _ownership(transaction, second))
    assert _worktree_snapshot(repository) == before


def test_write_bootstraps_a_missing_generated_root_inside_the_transaction(
    transaction: ModuleType,
    repository: Path,
) -> None:
    generated = repository / "schemas/telemetry/generated"
    generated.rmdir()
    assert not generated.exists()

    outputs = _outputs(transaction, 1)
    result = transaction.write_outputs(repository, outputs, {})

    assert result == transaction.RecoveryResult(False, "written")
    assert generated.is_dir() and not generated.is_symlink()
    _assert_outputs(repository, outputs)


@pytest.mark.skipif(not hasattr(os, "symlink"), reason="symlink unavailable")
def test_missing_generated_root_never_escapes_through_a_symlink_ancestor(
    transaction: ModuleType,
    tmp_path: Path,
) -> None:
    repository = tmp_path / "repository"
    (repository / ".git").mkdir(parents=True)
    (repository / "internal/observability").mkdir(parents=True)
    (repository / "schemas").mkdir()
    outside = tmp_path / "outside-telemetry"
    outside.mkdir()
    (repository / "schemas/telemetry").symlink_to(outside, target_is_directory=True)

    with pytest.raises(transaction.TransactionError, match="directory chain changed or is unsafe"):
        transaction.write_outputs(repository, _outputs(transaction, 1), {})

    assert not (outside / "generated").exists()
    assert _worktree_snapshot(repository) == {}


def test_check_mode_is_read_only_for_clean_drift_and_pending_recovery(
    transaction: ModuleType,
    repository: Path,
) -> None:
    first = _outputs(transaction, 1)
    transaction.write_outputs(repository, first, {})
    prior = _ownership(transaction, first)
    before = _worktree_snapshot(repository)
    transaction.check_outputs(repository, first, prior)
    assert _worktree_snapshot(repository) == before

    catalog = repository / "schemas/telemetry/generated/catalog.json"
    catalog.write_bytes(catalog.read_bytes().replace(b'"version": 1', b'"version": 9'))
    drifted = _worktree_snapshot(repository)
    with pytest.raises(transaction.GeneratedOutputDriftError, match="stale=.*catalog.json"):
        transaction.check_outputs(repository, first, prior)
    assert _worktree_snapshot(repository) == drifted

    catalog.write_bytes(first["schemas/telemetry/generated/catalog.json"].payload)

    class Crash(BaseException):
        pass

    def crash_after_apply(stage: str, _path: str | None) -> None:
        if stage == "after_output_apply":
            raise Crash

    with pytest.raises(Crash):
        transaction.write_outputs(repository, _outputs(transaction, 2), prior, fault_injector=crash_after_apply)
    interrupted = _worktree_snapshot(repository)
    with pytest.raises(transaction.RecoveryRequiredError):
        transaction.check_outputs(repository, first, prior)
    assert _worktree_snapshot(repository) == interrupted


@pytest.mark.parametrize(
    "path",
    [
        "/schemas/telemetry/generated/a.json",
        "schemas/telemetry/generated/../a.json",
        "schemas/telemetry/generated//a.json",
        "schemas\\telemetry\\generated\\a.json",
        "schemas/telemetry/generated",
        "schemas/telemetry/other.json",
        "internal/observability/generated.go",
        "internal/config/zz_generated_telemetry_registry.go",
    ],
)
def test_path_allowlist_rejects_noncanonical_or_unowned_roots(
    transaction: ModuleType,
    repository: Path,
    path: str,
) -> None:
    outputs = _outputs(transaction, 1, include_extra=False)
    outputs[path] = transaction.RenderedOutput(_json_payload(1, "bad"), JSON_MARKER)
    with pytest.raises(transaction.TransactionError):
        transaction.write_outputs(repository, outputs, {})


@pytest.mark.parametrize(
    ("output", "message"),
    [
        (lambda module: module.RenderedOutput(b"{}\n", JSON_MARKER), "ownership marker"),
        (
            lambda module: module.RenderedOutput(_json_payload(1, "mode"), JSON_MARKER, mode=0o755),
            "mode",
        ),
        (lambda _module: b"not-a-rendered-output", "in-memory bytes"),
    ],
)
def test_rendered_outputs_require_explicit_marker_mode_and_type(
    transaction: ModuleType,
    repository: Path,
    output: Callable[[ModuleType], Any],
    message: str,
) -> None:
    outputs = _outputs(transaction, 1, include_extra=False)
    outputs["schemas/telemetry/generated/bad.json"] = output(transaction)
    with pytest.raises(transaction.TransactionError, match=message):
        transaction.write_outputs(repository, outputs, {})


def test_manifest_is_mandatory(transaction: ModuleType, repository: Path) -> None:
    outputs = _outputs(transaction, 1)
    del outputs[transaction.MANIFEST_PATH]
    with pytest.raises(transaction.TransactionError, match="manifest commit marker"):
        transaction.write_outputs(repository, outputs, {})


def test_every_exact_internal_output_is_allowed_without_prefix_broadening(
    transaction: ModuleType,
    repository: Path,
) -> None:
    outputs = {
        transaction.MANIFEST_PATH: transaction.RenderedOutput(
            _json_payload(1, "manifest"),
            JSON_MARKER,
        )
    }
    for index, path in enumerate(sorted(transaction.EXACT_INTERNAL_OUTPUTS)):
        outputs[path] = transaction.RenderedOutput(
            (
                "// Code generated by DefenseClaw telemetry registry; DO NOT EDIT.\n"
                f"package observability\n\nconst generatedFile{index} = {index}\n"
            ).encode(),
            GO_MARKER,
        )
    transaction.write_outputs(repository, outputs, {})
    transaction.check_outputs(repository, outputs, _ownership(transaction, outputs))
    _assert_outputs(repository, outputs)

    broadened = dict(outputs)
    broadened["internal/observability/zz_generated_telemetry_ids_extra.go"] = transaction.RenderedOutput(
        b"// Code generated by DefenseClaw telemetry registry; DO NOT EDIT.\npackage observability\n",
        GO_MARKER,
    )
    with pytest.raises(transaction.TransactionError, match="outside the allowlist"):
        transaction.write_outputs(repository, broadened, _ownership(transaction, outputs))


@pytest.mark.parametrize(
    ("inventory", "message"),
    [("outputs", "generated output inventory"), ("prior", "prior ownership inventory")],
)
def test_exact_internal_outputs_are_an_all_or_none_inventory(
    transaction: ModuleType,
    repository: Path,
    inventory: str,
    message: str,
) -> None:
    outputs = _outputs(transaction, 1, include_extra=False)
    missing = sorted(transaction.EXACT_INTERNAL_OUTPUTS)[0]
    if inventory == "outputs":
        del outputs[missing]
        prior: dict[str, Any] = {}
    else:
        prior = _ownership(transaction, outputs)
        del prior[missing]

    with pytest.raises(transaction.TransactionError, match=f"{message}.*none or all"):
        transaction.write_outputs(repository, outputs, prior)


def test_unowned_collision_is_rejected_even_when_bytes_match(
    transaction: ModuleType,
    repository: Path,
) -> None:
    outputs = _outputs(transaction, 1, include_extra=False)
    catalog_path = "schemas/telemetry/generated/catalog.json"
    (repository / catalog_path).write_bytes(outputs[catalog_path].payload)
    before = _worktree_snapshot(repository)
    with pytest.raises(transaction.TransactionError, match="unowned.*collision"):
        transaction.write_outputs(repository, outputs, {})
    assert _worktree_snapshot(repository) == before
    with pytest.raises(transaction.GeneratedOutputDriftError, match="unowned="):
        transaction.check_outputs(repository, outputs, {})


@pytest.mark.skipif(not hasattr(os, "symlink"), reason="symlink unavailable")
def test_symlink_target_and_parent_are_rejected_without_following(
    transaction: ModuleType,
    repository: Path,
) -> None:
    outside = repository.parent / "outside"
    outside.write_text("do-not-touch", encoding="utf-8")
    outputs = _outputs(transaction, 1, include_extra=False)
    catalog = repository / "schemas/telemetry/generated/catalog.json"
    catalog.symlink_to(outside)
    with pytest.raises(transaction.TransactionError, match="unowned.*collision"):
        transaction.write_outputs(repository, outputs, {})
    assert outside.read_text(encoding="utf-8") == "do-not-touch"

    catalog.unlink()
    generated = repository / "schemas/telemetry/generated"
    generated.rmdir()
    generated.symlink_to(repository.parent)
    with pytest.raises(transaction.TransactionError, match="not a real directory"):
        transaction.write_outputs(repository, outputs, {})
    assert outside.read_text(encoding="utf-8") == "do-not-touch"


def test_nonregular_and_hardlinked_prior_outputs_are_rejected(
    transaction: ModuleType,
    repository: Path,
) -> None:
    first = _outputs(transaction, 1, include_extra=False)
    transaction.write_outputs(repository, first, {})
    prior = _ownership(transaction, first)
    catalog = repository / "schemas/telemetry/generated/catalog.json"
    catalog.unlink()
    catalog.mkdir()
    with pytest.raises(transaction.TransactionError, match="not a regular file"):
        transaction.write_outputs(repository, _outputs(transaction, 2, include_extra=False), prior)

    catalog.rmdir()
    catalog.write_bytes(first["schemas/telemetry/generated/catalog.json"].payload)
    alias = repository / "schemas/telemetry/generated/catalog-hardlink.json"
    os.link(catalog, alias)
    with pytest.raises(transaction.TransactionError, match="multiple hard links"):
        transaction.write_outputs(repository, _outputs(transaction, 2, include_extra=False), prior)


@pytest.mark.parametrize("tamper", ["bytes", "mode", "marker"])
def test_prior_ownership_drift_is_never_overwritten_or_deleted(
    transaction: ModuleType,
    repository: Path,
    tamper: str,
) -> None:
    first = _outputs(transaction, 1)
    transaction.write_outputs(repository, first, {})
    prior = _ownership(transaction, first)
    extra_path = "schemas/telemetry/generated/otlp-fixtures/cases/case.json"
    extra = repository / extra_path
    if tamper == "bytes":
        extra.write_bytes(extra.read_bytes() + b"manual\n")
    elif tamper == "mode":
        extra.chmod(0o600)
    else:
        payload = extra.read_bytes().replace(JSON_MARKER, b'"manually-owned"')
        extra.write_bytes(payload)
        prior[extra_path] = transaction.PriorOwnedOutput(
            sha256=transaction._sha256(payload),
            marker=JSON_MARKER,
        )
    before = _worktree_snapshot(repository)
    with pytest.raises((transaction.TransactionError, transaction.GeneratedOutputDriftError)):
        transaction.write_outputs(repository, _outputs(transaction, 2, include_extra=False), prior)
    assert _worktree_snapshot(repository) == before


@pytest.mark.parametrize(
    "failure_stage",
    [
        "stage_created",
        "output_staged",
        "staging_fsynced",
        "output_backed_up",
        "backups_complete",
        "transaction_ancestors_fsynced",
        "journal_prepared",
        "target_directories_created",
        "before_output_apply",
        "after_output_apply",
        "before_output_delete",
        "after_output_delete",
        "before_manifest_apply",
        "after_manifest_apply",
    ],
)
def test_caught_failure_at_each_mutating_stage_rolls_back_exactly(
    transaction: ModuleType,
    repository: Path,
    failure_stage: str,
) -> None:
    first = _outputs(transaction, 1)
    transaction.write_outputs(repository, first, {})
    before = _worktree_snapshot(repository)
    seen = False

    def fail(stage: str, _path: str | None) -> None:
        nonlocal seen
        if stage == failure_stage and not seen:
            seen = True
            raise RuntimeError("injected")

    with pytest.raises(transaction.TransactionError, match="rolled back"):
        transaction.write_outputs(
            repository,
            _outputs(transaction, 2, include_extra=False),
            _ownership(transaction, first),
            fault_injector=fail,
        )
    assert seen
    assert _worktree_snapshot(repository) == before
    state = repository / transaction.STATE_DIRECTORY.as_posix()
    assert not (state / transaction.JOURNAL_NAME).exists()
    transaction.check_outputs(repository, first, _ownership(transaction, first))


@pytest.mark.parametrize("failure_stage", ["lock_acquired", "recovery_checked", "outputs_validated"])
def test_preparation_faults_release_lock_without_touching_outputs(
    transaction: ModuleType,
    repository: Path,
    failure_stage: str,
) -> None:
    outputs = _outputs(transaction, 1)

    def fail(stage: str, _path: str | None) -> None:
        if stage == failure_stage:
            raise RuntimeError("injected")

    with pytest.raises(RuntimeError, match="injected"):
        transaction.write_outputs(repository, outputs, {}, fault_injector=fail)
    assert _worktree_snapshot(repository) == {}
    transaction.write_outputs(repository, outputs, {})


@pytest.mark.parametrize(
    ("failure_stage", "journal_expected"),
    [("journal_committed", True), ("cleanup_complete", False)],
)
def test_post_commit_fault_never_rolls_back_published_manifest(
    transaction: ModuleType,
    repository: Path,
    failure_stage: str,
    journal_expected: bool,
) -> None:
    first = _outputs(transaction, 1)
    second = _outputs(transaction, 2, include_extra=False)
    transaction.write_outputs(repository, first, {})

    def fail(stage: str, _path: str | None) -> None:
        if stage == failure_stage:
            raise RuntimeError("post-commit")

    with pytest.raises(transaction.TransactionError, match="committed"):
        transaction.write_outputs(
            repository,
            second,
            _ownership(transaction, first),
            fault_injector=fail,
        )
    _assert_outputs(repository, second)
    state = repository / transaction.STATE_DIRECTORY.as_posix()
    assert (state / transaction.JOURNAL_NAME).exists() is journal_expected
    if journal_expected:
        assert transaction.recover_outputs(repository) == transaction.RecoveryResult(True, "completed")
    transaction.check_outputs(repository, second, _ownership(transaction, second))


def test_failure_between_data_and_manifest_observes_old_manifest_then_rolls_back(
    transaction: ModuleType,
    repository: Path,
) -> None:
    first = _outputs(transaction, 1, include_extra=False)
    second = _outputs(transaction, 2, include_extra=False)
    transaction.write_outputs(repository, first, {})
    observed = False

    def fail(stage: str, path: str | None) -> None:
        nonlocal observed
        if stage == "after_output_apply" and path == "schemas/telemetry/generated/catalog.json":
            observed = True
            assert (repository / transaction.MANIFEST_PATH).read_bytes() == first[transaction.MANIFEST_PATH].payload
            assert (repository / path).read_bytes() == second[path].payload
            raise RuntimeError("stop before manifest")

    with pytest.raises(transaction.TransactionError, match="rolled back"):
        transaction.write_outputs(
            repository,
            second,
            _ownership(transaction, first),
            fault_injector=fail,
        )
    assert observed
    _assert_outputs(repository, first)


def test_process_interruption_recovers_prepared_transaction_by_rollback(
    transaction: ModuleType,
    repository: Path,
) -> None:
    first = _outputs(transaction, 1)
    second = _outputs(transaction, 2, include_extra=False)
    transaction.write_outputs(repository, first, {})

    class Crash(BaseException):
        pass

    def crash(stage: str, _path: str | None) -> None:
        if stage == "after_output_apply":
            raise Crash

    with pytest.raises(Crash):
        transaction.write_outputs(
            repository,
            second,
            _ownership(transaction, first),
            fault_injector=crash,
        )
    state = repository / transaction.STATE_DIRECTORY.as_posix()
    assert (state / transaction.JOURNAL_NAME).is_file()
    result = transaction.recover_outputs(repository)
    assert result == transaction.RecoveryResult(True, "rolled_back")
    _assert_outputs(repository, first)
    assert not (state / transaction.JOURNAL_NAME).exists()


def test_exact_seven_interruption_requires_recovery_before_readers_resume(
    transaction: ModuleType,
    repository: Path,
) -> None:
    first = _outputs(transaction, 1, include_extra=False)
    second = _outputs(transaction, 2, include_extra=False)
    transaction.write_outputs(repository, first, {})
    prior = _ownership(transaction, first)
    state = repository / transaction.STATE_DIRECTORY.as_posix()

    class Crash(BaseException):
        pass

    def go_generation_versions() -> set[int]:
        versions: set[int] = set()
        for path in transaction.EXACT_INTERNAL_OUTPUTS:
            payload = (repository / path).read_text(encoding="utf-8")
            if " = 1\n" in payload:
                versions.add(1)
            if " = 2\n" in payload:
                versions.add(2)
        return versions

    witnessed = False

    def crash_after_first_go_apply(stage: str, path: str | None) -> None:
        nonlocal witnessed
        if stage != "after_output_apply" or path not in transaction.EXACT_INTERNAL_OUTPUTS:
            return
        witnessed = True
        assert go_generation_versions() == {1, 2}
        assert (repository / transaction.MANIFEST_PATH).read_bytes() == first[transaction.MANIFEST_PATH].payload
        journal = transaction._read_journal(state)
        assert journal is not None and journal.phase == "prepared"
        with pytest.raises(transaction.RecoveryRequiredError):
            transaction.check_outputs(repository, first, prior)
        raise Crash

    with pytest.raises(Crash):
        transaction.write_outputs(
            repository,
            second,
            prior,
            fault_injector=crash_after_first_go_apply,
        )

    assert witnessed
    assert go_generation_versions() == {1, 2}
    with pytest.raises(transaction.RecoveryRequiredError):
        transaction.check_outputs(repository, first, prior)
    assert transaction.recover_outputs(repository) == transaction.RecoveryResult(True, "rolled_back")
    _assert_outputs(repository, first)


def test_process_interruption_after_commit_completes_cleanup_without_rollback(
    transaction: ModuleType,
    repository: Path,
) -> None:
    first = _outputs(transaction, 1)
    second = _outputs(transaction, 2, include_extra=False)
    transaction.write_outputs(repository, first, {})

    class Crash(BaseException):
        pass

    def crash(stage: str, _path: str | None) -> None:
        if stage == "journal_committed":
            raise Crash

    with pytest.raises(Crash):
        transaction.write_outputs(
            repository,
            second,
            _ownership(transaction, first),
            fault_injector=crash,
        )
    result = transaction.recover_outputs(repository)
    assert result == transaction.RecoveryResult(True, "completed")
    _assert_outputs(repository, second)


def test_recovery_can_resume_after_crash_at_recovery_start(
    transaction: ModuleType,
    repository: Path,
) -> None:
    first = _outputs(transaction, 1)
    second = _outputs(transaction, 2, include_extra=False)
    transaction.write_outputs(repository, first, {})

    class Crash(BaseException):
        pass

    def interrupt_write(stage: str, _path: str | None) -> None:
        if stage == "after_output_apply":
            raise Crash

    with pytest.raises(Crash):
        transaction.write_outputs(
            repository,
            second,
            _ownership(transaction, first),
            fault_injector=interrupt_write,
        )

    def interrupt_recovery(stage: str, _path: str | None) -> None:
        if stage == "recovery_started":
            raise Crash

    with pytest.raises(Crash):
        transaction.recover_outputs(repository, fault_injector=interrupt_recovery)
    assert transaction.recover_outputs(repository) == transaction.RecoveryResult(True, "rolled_back")
    _assert_outputs(repository, first)


def test_recovery_can_resume_partially_completed_output_rollback(
    transaction: ModuleType,
    repository: Path,
) -> None:
    first = _outputs(transaction, 1)
    second = _outputs(transaction, 2, include_extra=False)
    transaction.write_outputs(repository, first, {})
    catalog_path = "schemas/telemetry/generated/catalog.json"
    go_path = "internal/observability/zz_generated_telemetry_ids.go"

    class Crash(BaseException):
        pass

    def interrupt_write(stage: str, path: str | None) -> None:
        if stage == "after_output_apply" and path == catalog_path:
            raise Crash

    with pytest.raises(Crash):
        transaction.write_outputs(
            repository,
            second,
            _ownership(transaction, first),
            fault_injector=interrupt_write,
        )

    rolled_back = 0

    def interrupt_recovery(stage: str, _path: str | None) -> None:
        nonlocal rolled_back
        if stage == "output_rolled_back":
            rolled_back += 1
            if rolled_back == 3:
                raise Crash

    with pytest.raises(Crash):
        transaction.recover_outputs(repository, fault_injector=interrupt_recovery)
    assert (repository / catalog_path).read_bytes() == first[catalog_path].payload
    assert (repository / go_path).read_bytes() == second[go_path].payload

    assert transaction.recover_outputs(repository) == transaction.RecoveryResult(True, "rolled_back")
    _assert_outputs(repository, first)


def test_recovery_after_crash_once_backups_are_removed_is_a_clean_noop(
    transaction: ModuleType,
    repository: Path,
) -> None:
    first = _outputs(transaction, 1)
    second = _outputs(transaction, 2, include_extra=False)
    transaction.write_outputs(repository, first, {})

    class Crash(BaseException):
        pass

    def interrupt_cleanup(stage: str, _path: str | None) -> None:
        if stage == "cleanup_backups_removed":
            raise Crash

    with pytest.raises(Crash):
        transaction.write_outputs(
            repository,
            second,
            _ownership(transaction, first),
            fault_injector=interrupt_cleanup,
        )

    state = repository / transaction.STATE_DIRECTORY.as_posix()
    assert not (state / transaction.JOURNAL_NAME).exists()
    assert not any((state / "transactions").iterdir())
    assert transaction.recover_outputs(repository) == transaction.RecoveryResult(False, "none")
    _assert_outputs(repository, second)


@pytest.mark.parametrize("phase", ["prepared", "committed"])
def test_recovery_rejects_leaf_swap_after_descriptor_read(
    transaction: ModuleType,
    repository: Path,
    monkeypatch: pytest.MonkeyPatch,
    phase: str,
) -> None:
    first = _outputs(transaction, 1, include_extra=False)
    second = _outputs(transaction, 2, include_extra=False)
    transaction.write_outputs(repository, first, {})
    target_path = "schemas/telemetry/generated/catalog.json"
    target = repository / target_path

    class Crash(BaseException):
        pass

    def crash(stage: str, path: str | None) -> None:
        if phase == "prepared" and stage == "after_output_apply" and path == target_path:
            raise Crash
        if phase == "committed" and stage == "journal_committed":
            raise Crash

    with pytest.raises(Crash):
        transaction.write_outputs(
            repository,
            second,
            _ownership(transaction, first),
            fault_injector=crash,
        )
    outside = repository.parent / f"outside-{phase}-recovery"
    outside.write_bytes(second[target_path].payload)
    outside_before = outside.read_bytes()
    original_stat = transaction.os.stat
    swapped = False

    def swap_after_open(
        path: Any,
        *,
        dir_fd: int | None = None,
        follow_symlinks: bool = True,
    ) -> os.stat_result:
        nonlocal swapped
        if path == target.name and dir_fd is not None and not follow_symlinks and not swapped:
            target.unlink()
            target.symlink_to(outside)
            swapped = True
        return original_stat(path, dir_fd=dir_fd, follow_symlinks=follow_symlinks)

    monkeypatch.setattr(transaction.os, "stat", swap_after_open)
    with pytest.raises(transaction.RollbackError):
        transaction.recover_outputs(repository)
    state = repository / transaction.STATE_DIRECTORY.as_posix()
    assert swapped
    assert target.is_symlink()
    assert outside.read_bytes() == outside_before
    assert (state / transaction.JOURNAL_NAME).exists()


def test_process_interruption_before_journal_discards_only_controlled_staging(
    transaction: ModuleType,
    repository: Path,
) -> None:
    outputs = _outputs(transaction, 1)

    class Crash(BaseException):
        pass

    def crash(stage: str, _path: str | None) -> None:
        if stage == "output_staged":
            raise Crash

    with pytest.raises(Crash):
        transaction.write_outputs(
            repository,
            outputs,
            {},
            fault_injector=crash,
        )
    assert _worktree_snapshot(repository) == {}
    result = transaction.recover_outputs(repository)
    assert result == transaction.RecoveryResult(True, "discarded_staging")
    assert _worktree_snapshot(repository) == {}


def test_pre_journal_cleanup_preserves_replaced_transaction_directory(
    transaction: ModuleType,
    repository: Path,
) -> None:
    outputs = _outputs(transaction, 1, include_extra=False)
    state = repository / transaction.STATE_DIRECTORY.as_posix()
    displaced = repository.parent / "displaced-pre-journal-transaction"
    replacement: Path | None = None

    def replace_then_fail(stage: str, _path: str | None) -> None:
        nonlocal replacement
        if stage != "output_staged" or replacement is not None:
            return
        transactions = state / "transactions"
        active = [candidate for candidate in transactions.iterdir() if candidate.is_dir()]
        assert len(active) == 1
        replacement = active[0]
        replacement.replace(displaced)
        replacement.mkdir()
        (replacement / "replacement-sentinel").write_text("preserve", encoding="utf-8")
        raise RuntimeError("fail after replacement")

    with pytest.raises(transaction.TransactionError, match="failed and was rolled back"):
        transaction.write_outputs(repository, outputs, {}, fault_injector=replace_then_fail)

    assert replacement is not None
    assert displaced.is_dir()
    assert (replacement / "replacement-sentinel").read_text(encoding="utf-8") == "preserve"
    with pytest.raises(transaction.RecoveryRequiredError):
        transaction.check_outputs(repository, outputs, {})
    assert (replacement / "replacement-sentinel").is_file()


def test_write_auto_recovers_interrupted_prior_transaction_before_new_validation(
    transaction: ModuleType,
    repository: Path,
) -> None:
    first = _outputs(transaction, 1, include_extra=False)
    second = _outputs(transaction, 2, include_extra=False)
    transaction.write_outputs(repository, first, {})

    class Crash(BaseException):
        pass

    def crash(stage: str, _path: str | None) -> None:
        if stage == "after_output_apply":
            raise Crash

    with pytest.raises(Crash):
        transaction.write_outputs(
            repository,
            second,
            _ownership(transaction, first),
            fault_injector=crash,
        )
    result = transaction.write_outputs(repository, second, _ownership(transaction, first))
    assert result == transaction.RecoveryResult(True, "written")
    _assert_outputs(repository, second)


def test_tampered_backup_prevents_unsafe_recovery_deletion(
    transaction: ModuleType,
    repository: Path,
) -> None:
    first = _outputs(transaction, 1, include_extra=False)
    transaction.write_outputs(repository, first, {})

    class Crash(BaseException):
        pass

    def crash(stage: str, _path: str | None) -> None:
        if stage == "after_output_apply":
            raise Crash

    with pytest.raises(Crash):
        transaction.write_outputs(
            repository,
            _outputs(transaction, 2, include_extra=False),
            _ownership(transaction, first),
            fault_injector=crash,
        )
    state = repository / transaction.STATE_DIRECTORY.as_posix()
    backup = next((state / "transactions").rglob("*.backup"))
    backup.write_bytes(b"tampered")
    with pytest.raises(transaction.RollbackError):
        transaction.recover_outputs(repository)
    assert (state / transaction.JOURNAL_NAME).exists()


def test_external_change_during_apply_is_not_overwritten_by_rollback(
    transaction: ModuleType,
    repository: Path,
) -> None:
    first = _outputs(transaction, 1, include_extra=False)
    transaction.write_outputs(repository, first, {})
    catalog_path = "schemas/telemetry/generated/catalog.json"
    catalog = repository / catalog_path
    manual = b"manual concurrent content\n"

    def change_target(stage: str, path: str | None) -> None:
        if stage == "after_output_apply" and path == catalog_path:
            catalog.write_bytes(manual)
            raise RuntimeError("external writer")

    with pytest.raises(transaction.RollbackError, match="rollback both failed"):
        transaction.write_outputs(
            repository,
            _outputs(transaction, 2, include_extra=False),
            _ownership(transaction, first),
            fault_injector=change_target,
        )
    assert catalog.read_bytes() == manual
    state = repository / transaction.STATE_DIRECTORY.as_posix()
    assert (state / transaction.JOURNAL_NAME).exists()


@pytest.mark.parametrize("operation", ["replace", "delete"])
def test_mutation_identity_guard_preserves_concurrent_unowned_swap(
    transaction: ModuleType,
    repository: Path,
    monkeypatch: pytest.MonkeyPatch,
    operation: str,
) -> None:
    first = _outputs(transaction, 1)
    transaction.write_outputs(repository, first, {})
    target_path = (
        "schemas/telemetry/generated/catalog.json"
        if operation == "replace"
        else "schemas/telemetry/generated/otlp-fixtures/cases/case.json"
    )
    target = repository / target_path
    concurrent = target.parent / "concurrent-unowned"
    manual = b"concurrent unowned content\n"
    concurrent.write_bytes(manual)

    if operation == "replace":
        original = transaction._replace_file_durable

        def swap_before_replace(
            staged: Path,
            candidate: Path,
            prior_state: Any,
            transaction_root: Path,
        ) -> None:
            if candidate == target and concurrent.exists():
                os.replace(concurrent, candidate)
            original(staged, candidate, prior_state, transaction_root)

        monkeypatch.setattr(transaction, "_replace_file_durable", swap_before_replace)
        second = _outputs(transaction, 2)
    else:
        original = transaction._delete_file_durable

        def swap_before_delete(
            candidate: Path,
            prior_state: Any,
            transaction_root: Path,
        ) -> None:
            if candidate == target and concurrent.exists():
                os.replace(concurrent, candidate)
            original(candidate, prior_state, transaction_root)

        monkeypatch.setattr(transaction, "_delete_file_durable", swap_before_delete)
        second = _outputs(transaction, 2, include_extra=False)

    with pytest.raises(transaction.RollbackError, match="rollback both failed"):
        transaction.write_outputs(repository, second, _ownership(transaction, first))

    assert target.read_bytes() == manual
    state = repository / transaction.STATE_DIRECTORY.as_posix()
    assert (state / transaction.JOURNAL_NAME).exists()


def test_previously_absent_target_uses_no_clobber_install(
    transaction: ModuleType,
    repository: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    first = _outputs(transaction, 1, include_extra=False)
    transaction.write_outputs(repository, first, {})
    second = _outputs(transaction, 2)
    path = "schemas/telemetry/generated/otlp-fixtures/cases/case.json"
    target = repository / path
    manual = b"concurrent new file\n"
    original = transaction._replace_file_durable

    def create_before_install(
        staged: Path,
        candidate: Path,
        prior_state: Any,
        transaction_root: Path,
    ) -> None:
        if candidate == target and not candidate.exists():
            candidate.write_bytes(manual)
        original(staged, candidate, prior_state, transaction_root)

    monkeypatch.setattr(transaction, "_replace_file_durable", create_before_install)
    with pytest.raises(transaction.RollbackError, match="rollback both failed"):
        transaction.write_outputs(repository, second, _ownership(transaction, first))
    assert target.read_bytes() == manual


def test_concurrent_creation_after_atomic_detach_is_not_overwritten(
    transaction: ModuleType,
    repository: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    first = _outputs(transaction, 1, include_extra=False)
    transaction.write_outputs(repository, first, {})
    target = repository / "schemas/telemetry/generated/catalog.json"
    manual = b"concurrent file after detach\n"
    original = transaction._rename_no_replace
    inserted = False

    def create_between_detach_and_install(source: Path, candidate: Path) -> None:
        nonlocal inserted
        if candidate == target and "/stage/" in source.as_posix() and not inserted:
            assert not candidate.exists()
            candidate.write_bytes(manual)
            inserted = True
        original(source, candidate)

    monkeypatch.setattr(transaction, "_rename_no_replace", create_between_detach_and_install)
    with pytest.raises(transaction.RollbackError, match="rollback both failed"):
        transaction.write_outputs(
            repository,
            _outputs(transaction, 2, include_extra=False),
            _ownership(transaction, first),
        )
    assert inserted
    assert target.read_bytes() == manual


@pytest.mark.skipif(not hasattr(os, "symlink"), reason="symlink unavailable")
def test_parent_swap_after_precondition_cannot_escape_repository(
    transaction: ModuleType,
    repository: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    first = _outputs(transaction, 1)
    transaction.write_outputs(repository, first, {})
    target = repository / "schemas/telemetry/generated/otlp-fixtures/cases/case.json"
    original_parent = target.parent
    detached_parent = original_parent.with_name("cases-before-swap")
    outside = repository.parent / "outside-parent-swap"
    outside.mkdir()
    original = transaction._replace_file_durable
    swapped = False

    def swap_parent_before_leaf_mutation(
        staged: Path,
        candidate: Path,
        prior_state: Any,
        transaction_root: Path,
    ) -> None:
        nonlocal swapped
        if candidate == target and not swapped:
            original_parent.rename(detached_parent)
            original_parent.symlink_to(outside, target_is_directory=True)
            swapped = True
        original(staged, candidate, prior_state, transaction_root)

    monkeypatch.setattr(transaction, "_replace_file_durable", swap_parent_before_leaf_mutation)
    with pytest.raises(transaction.RollbackError, match="rollback both failed"):
        transaction.write_outputs(repository, _outputs(transaction, 2), _ownership(transaction, first))

    assert swapped
    assert list(outside.iterdir()) == []
    assert (detached_parent / target.name).read_bytes() == first[target.relative_to(repository).as_posix()].payload


def test_crash_after_durable_journal_removal_leaves_recoverable_orphan_backups(
    transaction: ModuleType,
    repository: Path,
) -> None:
    first = _outputs(transaction, 1)
    transaction.write_outputs(repository, first, {})

    class Crash(BaseException):
        pass

    failed_apply = False

    def crash_during_rollback_cleanup(stage: str, _path: str | None) -> None:
        nonlocal failed_apply
        if stage == "after_output_apply" and not failed_apply:
            failed_apply = True
            raise RuntimeError("start rollback")
        if stage == "cleanup_journal_removed":
            raise Crash

    with pytest.raises(Crash):
        transaction.write_outputs(
            repository,
            _outputs(transaction, 2, include_extra=False),
            _ownership(transaction, first),
            fault_injector=crash_during_rollback_cleanup,
        )

    _assert_outputs(repository, first)
    state = repository / transaction.STATE_DIRECTORY.as_posix()
    assert not (state / transaction.JOURNAL_NAME).exists()
    assert any((state / "transactions").iterdir())
    assert transaction.recover_outputs(repository) == transaction.RecoveryResult(True, "discarded_staging")
    _assert_outputs(repository, first)


@pytest.mark.parametrize("phase", ["prepared", "committed"])
def test_post_rename_journal_sync_failure_preserves_phase_and_backups(
    transaction: ModuleType,
    repository: Path,
    phase: str,
) -> None:
    first = _outputs(transaction, 1)
    second = _outputs(transaction, 2, include_extra=False)
    transaction.write_outputs(repository, first, {})

    def fail_after_rename(stage: str, path: str | None) -> None:
        if stage == "journal_published" and path == phase:
            raise OSError("directory fsync failed")

    if phase == "prepared":
        with pytest.raises(transaction.TransactionError, match="rolled back"):
            transaction.write_outputs(
                repository,
                second,
                _ownership(transaction, first),
                fault_injector=fail_after_rename,
            )
        _assert_outputs(repository, first)
        state = repository / transaction.STATE_DIRECTORY.as_posix()
        assert not (state / transaction.JOURNAL_NAME).exists()
    else:
        with pytest.raises(transaction.TransactionError, match="cleanup requires recovery"):
            transaction.write_outputs(
                repository,
                second,
                _ownership(transaction, first),
                fault_injector=fail_after_rename,
            )
        _assert_outputs(repository, second)
        state = repository / transaction.STATE_DIRECTORY.as_posix()
        journal = transaction._read_journal(state)
        assert journal is not None and journal.phase == "committed"
        assert any((state / "transactions" / journal.token / "backup").iterdir())
        assert transaction.recover_outputs(repository) == transaction.RecoveryResult(True, "completed")


def test_maximum_inventory_is_rejected_when_exact_journal_would_be_unreadable(
    transaction: ModuleType,
) -> None:
    marker = b"x" * transaction.MAX_MARKER_BYTES
    outputs = {
        transaction.MANIFEST_PATH: transaction.RenderedOutput(marker + b"\n", marker),
    }
    long_directory = "p" * 200
    for index in range(1, transaction.MAX_OUTPUTS):
        path = f"schemas/telemetry/generated/bounded/{long_directory}/{index:04d}.json"
        outputs[path] = transaction.RenderedOutput(marker + b"\n", marker)
    prior = _ownership(transaction, outputs)

    with pytest.raises(transaction.TransactionError, match="journal exceeds its size limit"):
        transaction._planned_journal("0" * 32, outputs, prior, {}, ())


def test_new_transaction_ancestors_are_synced_before_journal_publication(
    transaction: ModuleType,
    repository: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    synced: list[Path] = []
    synced_trees: list[Path] = []
    original = transaction._fsync_directory
    original_tree = transaction._fsync_directory_tree

    def record(path: Path) -> None:
        synced.append(path)
        original(path)

    def record_tree(path: Path) -> None:
        synced_trees.append(path)
        original_tree(path)

    monkeypatch.setattr(transaction, "_fsync_directory", record)
    monkeypatch.setattr(transaction, "_fsync_directory_tree", record_tree)

    def assert_order(stage: str, path: str | None) -> None:
        if stage != "journal_published" or path != "prepared":
            return
        state = transaction._state_root(repository, create=False)
        transactions = state / "transactions"
        tokens = [candidate for candidate in transactions.iterdir() if candidate.is_dir()]
        assert len(tokens) == 1
        assert state in synced
        assert transactions in synced
        assert tokens[0] in synced_trees

    transaction.write_outputs(repository, _outputs(transaction, 1), {}, fault_injector=assert_order)


@pytest.mark.skipif(not hasattr(os, "symlink"), reason="symlink unavailable")
def test_directory_sync_never_follows_a_symlinked_path_or_tree_entry(
    transaction: ModuleType,
    tmp_path: Path,
) -> None:
    outside = tmp_path / "outside"
    outside.mkdir()
    linked_root = tmp_path / "linked-root"
    linked_root.symlink_to(outside, target_is_directory=True)
    with pytest.raises(transaction.TransactionError, match="directory chain changed or is unsafe"):
        transaction._fsync_directory(linked_root)

    tree = tmp_path / "tree"
    tree.mkdir()
    (tree / "linked-child").symlink_to(outside, target_is_directory=True)
    with pytest.raises(transaction.TransactionError, match="unsafe symlink"):
        transaction._fsync_directory_tree(tree)

    assert list(outside.iterdir()) == []


def test_file_mode_is_applied_before_file_fsync(
    transaction: ModuleType,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    events: list[tuple[str, int]] = []
    original_fchmod = os.fchmod
    original_fsync = os.fsync

    def record_fchmod(descriptor: int, mode: int) -> None:
        events.append(("chmod", descriptor))
        original_fchmod(descriptor, mode)

    def record_fsync(descriptor: int) -> None:
        events.append(("fsync", descriptor))
        original_fsync(descriptor)

    monkeypatch.setattr(transaction.os, "fchmod", record_fchmod)
    monkeypatch.setattr(transaction.os, "fsync", record_fsync)
    target = tmp_path / "durable"
    transaction._write_file_durable(target, b"payload", 0o644)
    descriptor = next(value for event, value in events if event == "chmod")
    assert events.index(("chmod", descriptor)) < events.index(("fsync", descriptor))
    assert stat.S_IMODE(target.stat().st_mode) == 0o644


def test_secure_tree_removal_supports_legacy_shutil_signature(
    transaction: ModuleType,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    parent = tmp_path / "transactions"
    tree = parent / ("a" * 32)
    (tree / "nested").mkdir(parents=True)
    (tree / "root-file").write_bytes(b"root")
    (tree / "nested/leaf-file").write_bytes(b"leaf")
    called = False

    def legacy_rmtree(path: str, ignore_errors: bool = False, onerror: Any = None) -> None:
        del path, ignore_errors, onerror
        nonlocal called
        called = True
        raise AssertionError("legacy shutil.rmtree must not receive dir_fd")

    monkeypatch.setattr(transaction.shutil, "rmtree", legacy_rmtree)
    transaction._secure_rmtree(parent, tree.name)

    assert not called
    assert not tree.exists()


def test_journal_mode_is_applied_before_journal_fsync(
    transaction: ModuleType,
    repository: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    state = transaction._state_root(repository, create=True)
    journal = transaction._planned_journal(
        "0" * 32,
        _outputs(transaction, 1, include_extra=False),
        {},
        {},
        (),
    )
    events: list[tuple[str, int]] = []
    original_fchmod = os.fchmod
    original_fsync = os.fsync

    def record_fchmod(descriptor: int, mode: int) -> None:
        events.append(("chmod", descriptor))
        original_fchmod(descriptor, mode)

    def record_fsync(descriptor: int) -> None:
        events.append(("fsync", descriptor))
        original_fsync(descriptor)

    monkeypatch.setattr(transaction.os, "fchmod", record_fchmod)
    monkeypatch.setattr(transaction.os, "fsync", record_fsync)
    transaction._write_journal(state, journal)
    descriptor = next(value for event, value in events if event == "chmod")
    assert events.index(("chmod", descriptor)) < events.index(("fsync", descriptor))
    assert stat.S_IMODE((state / transaction.JOURNAL_NAME).stat().st_mode) == 0o600


def test_exclusive_lock_rejects_concurrent_writer(
    transaction: ModuleType,
    repository: Path,
) -> None:
    state = transaction._state_root(repository, create=True)
    with transaction._exclusive_lock(state):
        with pytest.raises(transaction.TransactionBusyError):
            transaction.write_outputs(repository, _outputs(transaction, 1), {})
    transaction.write_outputs(repository, _outputs(transaction, 1), {})


def test_hardlinked_lock_file_is_rejected(transaction: ModuleType, repository: Path) -> None:
    state = transaction._state_root(repository, create=True)
    outside = repository.parent / "outside-lock"
    outside.write_text("lock", encoding="utf-8")
    os.link(outside, state / transaction.LOCK_NAME)
    with pytest.raises(transaction.TransactionError, match="lock is not a safe regular file"):
        transaction.write_outputs(repository, _outputs(transaction, 1), {})


def test_unsafe_state_lock_journal_and_staging_entries_fail_closed(
    transaction: ModuleType,
    repository: Path,
) -> None:
    state = repository / transaction.STATE_DIRECTORY.as_posix()
    state.mkdir(parents=True)
    state.chmod(0o700)
    journal = state / transaction.JOURNAL_NAME
    journal.write_text("not-json", encoding="utf-8")
    before = journal.read_bytes()
    with pytest.raises(transaction.RecoveryRequiredError):
        transaction.check_outputs(repository, _outputs(transaction, 1), {})
    assert journal.read_bytes() == before
    with pytest.raises(transaction.RecoveryRequiredError):
        transaction.recover_outputs(repository)

    journal.unlink()
    transactions = state / "transactions"
    transactions.mkdir()
    (transactions / "not-a-token").mkdir()
    with pytest.raises(transaction.RecoveryRequiredError, match="staging entry"):
        transaction.recover_outputs(repository)


@pytest.mark.skipif(not hasattr(os, "symlink"), reason="symlink unavailable")
def test_journal_leaf_swap_to_symlink_is_rejected_by_descriptor_read(
    transaction: ModuleType,
    repository: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    outputs = _outputs(transaction, 1, include_extra=False)

    class Crash(BaseException):
        pass

    def crash(stage: str, _path: str | None) -> None:
        if stage == "journal_prepared":
            raise Crash

    with pytest.raises(Crash):
        transaction.write_outputs(repository, outputs, {}, fault_injector=crash)
    state = repository / transaction.STATE_DIRECTORY.as_posix()
    journal = state / transaction.JOURNAL_NAME
    outside = repository.parent / "outside-journal"
    outside.write_bytes(journal.read_bytes())
    outside_before = outside.read_bytes()
    original_open = transaction.os.open
    swapped = False

    def swap_before_descriptor_open(
        path: Any,
        flags: int,
        mode: int = 0o777,
        *,
        dir_fd: int | None = None,
    ) -> int:
        nonlocal swapped
        if path == transaction.JOURNAL_NAME and dir_fd is not None and not swapped:
            journal.unlink()
            journal.symlink_to(outside)
            swapped = True
        return original_open(path, flags, mode, dir_fd=dir_fd)

    monkeypatch.setattr(transaction.os, "open", swap_before_descriptor_open)
    with pytest.raises(transaction.RecoveryRequiredError, match="safe regular file"):
        transaction.recover_outputs(repository)
    assert swapped
    assert journal.is_symlink()
    assert outside.read_bytes() == outside_before


def test_cleanup_rejects_same_bytes_journal_identity_swap(
    transaction: ModuleType,
    repository: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    outputs = _outputs(transaction, 1, include_extra=False)
    state = repository / transaction.STATE_DIRECTORY.as_posix()
    journal_path = state / transaction.JOURNAL_NAME
    displaced = repository.parent / "displaced-journal"
    original = transaction._rename_no_replace_at
    swapped = False

    def swap_before_retirement(
        source_descriptor: int,
        source_name: str,
        target_descriptor: int,
        target_name: str,
    ) -> int:
        nonlocal swapped
        if source_name == transaction.JOURNAL_NAME and target_name == "retired-journal.json" and not swapped:
            payload = journal_path.read_bytes()
            journal_path.replace(displaced)
            journal_path.write_bytes(payload)
            swapped = True
        return original(source_descriptor, source_name, target_descriptor, target_name)

    monkeypatch.setattr(transaction, "_rename_no_replace_at", swap_before_retirement)
    with pytest.raises(transaction.TransactionError, match="cleanup requires recovery"):
        transaction.write_outputs(repository, outputs, {})

    assert swapped
    assert displaced.is_file()
    assert journal_path.is_file()
    assert journal_path.read_bytes() == displaced.read_bytes()


def test_post_retirement_cleanup_preserves_replaced_transaction_directory(
    transaction: ModuleType,
    repository: Path,
) -> None:
    outputs = _outputs(transaction, 1, include_extra=False)
    state = repository / transaction.STATE_DIRECTORY.as_posix()
    displaced = repository.parent / "displaced-retired-transaction"
    replacement: Path | None = None

    def replace_after_retirement(stage: str, _path: str | None) -> None:
        nonlocal replacement
        if stage != "cleanup_journal_removed" or replacement is not None:
            return
        transactions = state / "transactions"
        active = [candidate for candidate in transactions.iterdir() if candidate.is_dir()]
        assert len(active) == 1
        replacement = active[0]
        replacement.replace(displaced)
        replacement.mkdir()
        (replacement / "replacement-sentinel").write_text("preserve", encoding="utf-8")

    with pytest.raises(transaction.TransactionError, match="committed before a post-commit failure"):
        transaction.write_outputs(repository, outputs, {}, fault_injector=replace_after_retirement)

    assert replacement is not None
    _assert_outputs(repository, outputs)
    assert (displaced / "retired-journal.json").is_file()
    assert (replacement / "replacement-sentinel").read_text(encoding="utf-8") == "preserve"
    with pytest.raises(transaction.RecoveryRequiredError):
        transaction.check_outputs(repository, outputs, _ownership(transaction, outputs))
    assert (replacement / "replacement-sentinel").is_file()


def test_journal_publication_rejects_entry_swap_before_identity_capture(
    transaction: ModuleType,
    repository: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    state = repository / transaction.STATE_DIRECTORY.as_posix()
    journal_path = state / transaction.JOURNAL_NAME
    displaced = repository.parent / "displaced-published-journal"
    original = transaction.os.stat
    swapped = False

    def swap_before_entry_stat(
        path: Any,
        *args: Any,
        dir_fd: int | None = None,
        follow_symlinks: bool = True,
        **kwargs: Any,
    ) -> os.stat_result:
        nonlocal swapped
        if path == transaction.JOURNAL_NAME and dir_fd is not None and not swapped:
            payload = journal_path.read_bytes()
            journal_path.replace(displaced)
            journal_path.write_bytes(payload)
            swapped = True
        return original(
            path,
            *args,
            dir_fd=dir_fd,
            follow_symlinks=follow_symlinks,
            **kwargs,
        )

    monkeypatch.setattr(transaction.os, "stat", swap_before_entry_stat)
    with pytest.raises(transaction.RollbackError, match="rollback both failed"):
        transaction.write_outputs(repository, _outputs(transaction, 1, include_extra=False), {})

    assert swapped
    assert displaced.is_file()
    assert journal_path.is_file()
    assert journal_path.read_bytes() == displaced.read_bytes()


def test_orphan_cleanup_rejects_directory_replacement_after_scan(
    transaction: ModuleType,
    repository: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    class Crash(BaseException):
        pass

    def crash(stage: str, _path: str | None) -> None:
        if stage == "output_staged":
            raise Crash

    with pytest.raises(Crash):
        transaction.write_outputs(
            repository,
            _outputs(transaction, 1, include_extra=False),
            {},
            fault_injector=crash,
        )

    state = repository / transaction.STATE_DIRECTORY.as_posix()
    transactions = state / "transactions"
    tokens = [candidate for candidate in transactions.iterdir() if candidate.is_dir()]
    assert len(tokens) == 1
    token = tokens[0]
    displaced = repository.parent / "displaced-orphan"
    original = transaction._secure_rmtree
    swapped = False

    def swap_after_scan(
        parent: Path,
        name: str,
        expected_identity: Any | None = None,
    ) -> None:
        nonlocal swapped
        if parent == transactions and name == token.name and not swapped:
            token.replace(displaced)
            token.mkdir()
            (token / "replacement-sentinel").write_text("preserve", encoding="utf-8")
            swapped = True
        original(parent, name, expected_identity)

    monkeypatch.setattr(transaction, "_secure_rmtree", swap_after_scan)
    with pytest.raises(transaction.RecoveryRequiredError, match="changed before removal"):
        transaction.recover_outputs(repository)

    assert swapped
    assert displaced.is_dir()
    assert (token / "replacement-sentinel").read_text(encoding="utf-8") == "preserve"


def test_journal_temporary_cleanup_rejects_file_replacement_after_scan(
    transaction: ModuleType,
    repository: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    state = transaction._state_root(repository, create=True)
    temporary = state / ".journal-repro.tmp"
    temporary.write_bytes(b"original")
    displaced = repository.parent / "displaced-journal-temporary"
    original = transaction._secure_remove_regular
    swapped = False

    def swap_after_scan(parent: Path, name: str, expected_identity: Any) -> None:
        nonlocal swapped
        if parent == state and name == temporary.name and not swapped:
            temporary.replace(displaced)
            temporary.write_bytes(b"replacement")
            swapped = True
        original(parent, name, expected_identity)

    monkeypatch.setattr(transaction, "_secure_remove_regular", swap_after_scan)
    with pytest.raises(transaction.RecoveryRequiredError, match="changed before removal"):
        transaction.recover_outputs(repository)

    assert swapped
    assert displaced.read_bytes() == b"original"
    assert temporary.read_bytes() == b"replacement"


def test_journal_cannot_claim_unrelated_directories_for_rollback_removal(
    transaction: ModuleType,
    repository: Path,
) -> None:
    outputs = _outputs(transaction, 1)

    class Crash(BaseException):
        pass

    def crash(stage: str, _path: str | None) -> None:
        if stage == "journal_prepared":
            raise Crash

    with pytest.raises(Crash):
        transaction.write_outputs(repository, outputs, {}, fault_injector=crash)
    state = repository / transaction.STATE_DIRECTORY.as_posix()
    journal_path = state / transaction.JOURNAL_NAME
    journal = json.loads(journal_path.read_bytes())
    journal["created_directories"] = ["internal/observability"]
    journal_path.write_bytes(transaction._canonical_json(journal))
    with pytest.raises(transaction.RecoveryRequiredError, match="created-directory set is unsafe"):
        transaction.recover_outputs(repository)
    assert (repository / "internal/observability").is_dir()


@pytest.mark.parametrize("section", ["prior", "desired"])
def test_invalid_journal_output_paths_are_recovery_errors(
    transaction: ModuleType,
    repository: Path,
    section: str,
) -> None:
    outputs = _outputs(transaction, 1, include_extra=False)

    class Crash(BaseException):
        pass

    def crash(stage: str, _path: str | None) -> None:
        if stage == "journal_prepared":
            raise Crash

    with pytest.raises(Crash):
        transaction.write_outputs(repository, outputs, {}, fault_injector=crash)
    state = repository / transaction.STATE_DIRECTORY.as_posix()
    journal_path = state / transaction.JOURNAL_NAME
    journal = json.loads(journal_path.read_bytes())
    journal[section][0]["path"] = "../outside"
    journal_path.write_bytes(transaction._canonical_json(journal))

    with pytest.raises(transaction.RecoveryRequiredError, match=rf"journal {section} path is invalid"):
        transaction.recover_outputs(repository)


@pytest.mark.parametrize(
    ("malformation", "message"),
    [
        ("desired-mode", "journal desired mode is invalid"),
        ("desired-marker", "journal marker is invalid"),
        ("prior-marker", "journal marker is invalid"),
        ("phase-type", "journal version or phase is invalid"),
        ("format-version-type", "journal version or phase is invalid"),
    ],
)
def test_canonical_malformed_journal_fields_are_recovery_errors(
    transaction: ModuleType,
    repository: Path,
    malformation: str,
    message: str,
) -> None:
    first = _outputs(transaction, 1, include_extra=False)
    outputs = _outputs(transaction, 2, include_extra=False)
    transaction.write_outputs(repository, first, {})

    class Crash(BaseException):
        pass

    def crash(stage: str, _path: str | None) -> None:
        if stage == "journal_prepared":
            raise Crash

    with pytest.raises(Crash):
        transaction.write_outputs(
            repository,
            outputs,
            _ownership(transaction, first),
            fault_injector=crash,
        )
    state = repository / transaction.STATE_DIRECTORY.as_posix()
    journal_path = state / transaction.JOURNAL_NAME
    journal = json.loads(journal_path.read_bytes())
    if malformation == "desired-mode":
        journal["desired"][0]["mode"] = 0o600
    elif malformation == "desired-marker":
        journal["desired"][0]["marker"] = ""
    elif malformation == "prior-marker":
        journal["prior"][0]["marker"] = ""
    elif malformation == "phase-type":
        journal["phase"] = []
    else:
        journal["format_version"] = True
    journal_path.write_bytes(transaction._canonical_json(journal))

    with pytest.raises(transaction.RecoveryRequiredError, match=message):
        transaction.recover_outputs(repository)


def test_journal_cannot_claim_unrelated_sibling_detach_paths(
    transaction: ModuleType,
    repository: Path,
) -> None:
    first = _outputs(transaction, 1, include_extra=False)
    transaction.write_outputs(repository, first, {})

    class Crash(BaseException):
        pass

    def crash(stage: str, _path: str | None) -> None:
        if stage == "journal_prepared":
            raise Crash

    with pytest.raises(Crash):
        transaction.write_outputs(
            repository,
            _outputs(transaction, 2, include_extra=False),
            _ownership(transaction, first),
            fault_injector=crash,
        )
    state = repository / transaction.STATE_DIRECTORY.as_posix()
    journal_path = state / transaction.JOURNAL_NAME
    journal = json.loads(journal_path.read_bytes())
    journal["prior"][0]["apply_detached"] = "schemas/telemetry/generated/unrelated.json"
    journal_path.write_bytes(transaction._canonical_json(journal))

    with pytest.raises(transaction.RecoveryRequiredError, match="detached path is invalid"):
        transaction.recover_outputs(repository)
    _assert_outputs(repository, first)


def test_state_directory_permissions_fail_closed(transaction: ModuleType, repository: Path) -> None:
    state = repository / transaction.STATE_DIRECTORY.as_posix()
    state.mkdir(parents=True)
    state.chmod(0o755)
    with pytest.raises(transaction.TransactionError, match="state permissions are unsafe"):
        transaction.write_outputs(repository, _outputs(transaction, 1), {})


def test_stale_owned_extra_is_reported_but_never_deleted_in_check_mode(
    transaction: ModuleType,
    repository: Path,
) -> None:
    first = _outputs(transaction, 1)
    transaction.write_outputs(repository, first, {})
    second = _outputs(transaction, 2, include_extra=False)
    before = _worktree_snapshot(repository)
    with pytest.raises(transaction.GeneratedOutputDriftError, match="extra=.*case.json"):
        transaction.check_outputs(repository, second, _ownership(transaction, first))
    assert _worktree_snapshot(repository) == before


def test_missing_or_invalid_git_state_root_is_rejected(
    transaction: ModuleType,
    tmp_path: Path,
) -> None:
    root = tmp_path / "repository"
    (root / "schemas/telemetry/generated").mkdir(parents=True)
    (root / "internal/observability").mkdir(parents=True)
    with pytest.raises(transaction.TransactionError, match=".git metadata is missing"):
        transaction.write_outputs(root, _outputs(transaction, 1), {})

    (root / ".git").write_text("gitdir: elsewhere\n", encoding="utf-8")
    with pytest.raises(transaction.TransactionError, match="target does not exist"):
        transaction.write_outputs(root, _outputs(transaction, 1), {})


@pytest.mark.parametrize("absolute", [False, True], ids=["relative", "absolute"])
def test_linked_worktree_gitfile_uses_per_worktree_gitdir_state(
    transaction: ModuleType,
    tmp_path: Path,
    absolute: bool,
) -> None:
    repository = _worktree_repository(tmp_path)
    gitdir = (tmp_path / "absolute-worktree-gitdir") if absolute else (repository / ".worktree-gitdir")
    gitdir.mkdir()
    pointer = gitdir.as_posix() if absolute else ".worktree-gitdir"
    (repository / ".git").write_text(f"gitdir: {pointer}\n", encoding="utf-8")
    outputs = _outputs(transaction, 1)

    transaction.write_outputs(repository, outputs, {})

    _assert_outputs(repository, outputs)
    transaction.check_outputs(repository, outputs, _ownership(transaction, outputs))
    state = gitdir / transaction.STATE_SUBDIRECTORY
    assert state.is_dir()
    assert not (repository / transaction.STATE_DIRECTORY.as_posix()).exists()


@pytest.mark.skipif(not hasattr(os, "symlink"), reason="symlink unavailable")
def test_repository_and_linked_gitdir_allow_canonical_symlinked_ancestors(
    transaction: ModuleType,
    tmp_path: Path,
) -> None:
    real_parent = tmp_path / "real-parent"
    real_parent.mkdir()
    repository = real_parent / "repository"
    (repository / ".git").mkdir(parents=True)
    (repository / "schemas/telemetry/generated").mkdir(parents=True)
    (repository / "internal/observability").mkdir(parents=True)
    parent_alias = tmp_path / "parent-alias"
    parent_alias.symlink_to(real_parent, target_is_directory=True)
    aliased_repository = parent_alias / "repository"
    outputs = _outputs(transaction, 1, include_extra=False)

    transaction.write_outputs(aliased_repository, outputs, {})
    _assert_outputs(repository, outputs)

    worktree = _worktree_repository(tmp_path / "linked")
    metadata_parent = tmp_path / "metadata-real"
    gitdir = metadata_parent / "worktree-gitdir"
    gitdir.mkdir(parents=True)
    metadata_alias = tmp_path / "metadata-alias"
    metadata_alias.symlink_to(metadata_parent, target_is_directory=True)
    (worktree / ".git").write_text(f"gitdir: {(metadata_alias / 'worktree-gitdir').as_posix()}\n", encoding="utf-8")

    transaction.write_outputs(worktree, outputs, {})
    assert (gitdir / transaction.STATE_SUBDIRECTORY).is_dir()


@pytest.mark.parametrize(
    "payload",
    [
        b"gitdir:relative\n",
        b"gitdir: \n",
        b"gitdir: relative\r\n",
        b"gitdir: relative\nextra\n",
        b"gitdir: relative\x00\n",
        b"not-gitdir: relative\n",
        b"gitdir: ./relative\n",
        b"gitdir: relative/../target\n",
        b"gitdir: relative//target\n",
        b"gitdir: relative/\n",
        b"gitdir: relative\\target\n",
    ],
)
def test_linked_worktree_gitfile_rejects_malformed_or_traversal_grammar(
    transaction: ModuleType,
    tmp_path: Path,
    payload: bytes,
) -> None:
    repository = _worktree_repository(tmp_path)
    (repository / "relative").mkdir()
    (repository / "target").mkdir()
    (repository / ".git").write_bytes(payload)
    before = _worktree_snapshot(repository)
    with pytest.raises(transaction.TransactionError):
        transaction.write_outputs(repository, _outputs(transaction, 1), {})
    assert _worktree_snapshot(repository) == before


def test_linked_worktree_gitfile_rejects_oversize_and_hardlinks(
    transaction: ModuleType,
    tmp_path: Path,
) -> None:
    repository = _worktree_repository(tmp_path / "oversize")
    (repository / ".git").write_bytes(b"gitdir: " + b"a" * transaction.MAX_GITFILE_BYTES + b"\n")
    with pytest.raises(transaction.TransactionError, match="indirection file is unsafe"):
        transaction.write_outputs(repository, _outputs(transaction, 1), {})

    repository = _worktree_repository(tmp_path / "hardlink")
    target = repository / ".worktree-gitdir"
    target.mkdir()
    source = tmp_path / "gitfile-source"
    source.write_text("gitdir: .worktree-gitdir\n", encoding="utf-8")
    os.link(source, repository / ".git")
    with pytest.raises(transaction.TransactionError, match="indirection file is unsafe"):
        transaction.write_outputs(repository, _outputs(transaction, 1), {})


def test_linked_worktree_gitfile_rejects_same_length_in_place_rewrite(
    transaction: ModuleType,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    repository = _worktree_repository(tmp_path)
    (repository / ".worktree-a").mkdir()
    (repository / ".worktree-b").mkdir()
    gitfile = repository / ".git"
    original_payload = b"gitdir: .worktree-a\n"
    replacement_payload = b"gitdir: .worktree-b\n"
    assert len(original_payload) == len(replacement_payload)
    gitfile.write_bytes(original_payload)
    before = _worktree_snapshot(repository)
    original = transaction.os.read
    rewritten = False

    def rewrite_during_read(descriptor: int, size: int) -> bytes:
        nonlocal rewritten
        if not rewritten:
            gitfile.write_bytes(replacement_payload)
            rewritten = True
        return original(descriptor, size)

    monkeypatch.setattr(transaction.os, "read", rewrite_during_read)
    with pytest.raises(transaction.TransactionError, match="cannot safely read"):
        transaction.write_outputs(repository, _outputs(transaction, 1), {})

    assert rewritten
    assert gitfile.read_bytes() == replacement_payload
    assert _worktree_snapshot(repository) == before
    assert not (repository / ".worktree-a" / transaction.STATE_SUBDIRECTORY).exists()
    assert not (repository / ".worktree-b" / transaction.STATE_SUBDIRECTORY).exists()


def test_linked_worktree_gitdir_rejects_symlink_components_and_non_directory(
    transaction: ModuleType,
    tmp_path: Path,
) -> None:
    repository = _worktree_repository(tmp_path / "symlink")
    real = tmp_path / "real-gitdir"
    real.mkdir()
    link = repository / "linked-gitdir"
    link.symlink_to(real, target_is_directory=True)
    (repository / ".git").write_text("gitdir: linked-gitdir\n", encoding="utf-8")
    with pytest.raises(transaction.TransactionError, match="not a real directory chain"):
        transaction.write_outputs(repository, _outputs(transaction, 1), {})

    repository = _worktree_repository(tmp_path / "component")
    metadata = repository / "metadata"
    metadata.mkdir()
    (metadata / "link").symlink_to(real, target_is_directory=True)
    (repository / ".git").write_text("gitdir: metadata/link\n", encoding="utf-8")
    with pytest.raises(transaction.TransactionError, match="not a real directory chain"):
        transaction.write_outputs(repository, _outputs(transaction, 1), {})

    repository = _worktree_repository(tmp_path / "file")
    (repository / "gitdir-file").write_text("not a directory", encoding="utf-8")
    (repository / ".git").write_text("gitdir: gitdir-file\n", encoding="utf-8")
    with pytest.raises(transaction.TransactionError, match="not a real directory chain"):
        transaction.write_outputs(repository, _outputs(transaction, 1), {})


def test_git_metadata_symlink_is_rejected(transaction: ModuleType, tmp_path: Path) -> None:
    repository = _worktree_repository(tmp_path)
    real = repository / ".real-gitdir"
    real.mkdir()
    (repository / ".git").symlink_to(real, target_is_directory=True)
    with pytest.raises(transaction.TransactionError, match="metadata is missing or unsafe"):
        transaction.write_outputs(repository, _outputs(transaction, 1), {})
