// Copyright 2026 Cisco Systems, Inc. and its affiliates
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// SPDX-License-Identifier: Apache-2.0

// Package profilemanifest reads the generated compatibility-profile authority.
// It deliberately derives eligibility from generated bytes instead of keeping
// another handwritten family allowlist in a destination implementation.
package profilemanifest

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"sort"
	"sync"

	"github.com/defenseclaw/defenseclaw/internal/observability"
	publicschemas "github.com/defenseclaw/defenseclaw/schemas"
)

const manifestFormat = "defenseclaw-compatibility-profile-v1"

// Manifest is one generated compatibility-profile authority document.
type Manifest struct {
	Format               string            `json:"format"`
	ProfileID            string            `json:"profile_id"`
	Availability         string            `json:"availability"`
	SchemaVersion        int               `json:"schema_version"`
	RegistryVersion      int               `json:"registry_version"`
	BucketCatalogVersion int               `json:"bucket_catalog_version"`
	MaterializedView     string            `json:"materialized_view_sha256"`
	RuntimeProjection    RuntimeProjection `json:"runtime_projection"`
	Families             []Family          `json:"families"`
	Generated            generatedMarker   `json:"x-defenseclaw-generated"`
}

// RuntimeProjection describes whether a runtime converter exists and its
// closed behavior for unsupported records.
type RuntimeProjection struct {
	Status                string           `json:"status"`
	Input                 string           `json:"input"`
	Mode                  string           `json:"mode"`
	UnsupportedBehavior   string           `json:"unsupported_behavior"`
	Reason                string           `json:"reason,omitempty"`
	AttributeAliases      []AttributeAlias `json:"attribute_aliases,omitempty"`
	EventAliasSources     []string         `json:"event_alias_sources,omitempty"`
	AliasConflictBehavior string           `json:"alias_conflict_behavior,omitempty"`
}

// AttributeAlias is one source-to-projection alias owned by a profile.
type AttributeAlias struct {
	Source       string `json:"source"`
	Target       string `json:"target"`
	EventDerived bool   `json:"event_derived"`
}

// Family is one exact generated profile membership and projection contract.
type Family struct {
	FamilyID    string                  `json:"family_id"`
	Signal      observability.Signal    `json:"signal"`
	Bucket      observability.Bucket    `json:"bucket"`
	EventName   observability.EventName `json:"event_name"`
	Eligibility string                  `json:"eligibility"`
	Projection  Projection              `json:"projection"`
}

// Projection is the closed union of generated projection facts used by the
// current Galileo/local implementations or the explicit unsupported arm.
type Projection struct {
	Mode                  string          `json:"mode"`
	Behavior              string          `json:"behavior,omitempty"`
	Reason                string          `json:"reason,omitempty"`
	Shape                 string          `json:"shape,omitempty"`
	OperationAttribute    *string         `json:"operation_attribute,omitempty"`
	AllowedOperations     []string        `json:"allowed_operations,omitempty"`
	OpenInferenceSpanKind string          `json:"openinference_span_kind,omitempty"`
	AllowedSpanKinds      []string        `json:"allowed_span_kinds,omitempty"`
	RequiredAttributes    []string        `json:"required_attributes,omitempty"`
	InstrumentType        string          `json:"instrument_type,omitempty"`
	ValueType             string          `json:"value_type,omitempty"`
	Unit                  string          `json:"unit,omitempty"`
	Temporality           string          `json:"temporality,omitempty"`
	Boundaries            []float64       `json:"boundaries,omitempty"`
	CardinalityLimit      int             `json:"cardinality_limit,omitempty"`
	LabelProjection       LabelProjection `json:"label_projection,omitempty"`
}

// LabelProjection preserves the exact current metric attribute-to-label map.
type LabelProjection struct {
	Profile           string     `json:"profile"`
	Mappings          [][]string `json:"mappings"`
	EmptyLabelsReason string     `json:"empty_labels_reason,omitempty"`
	IdentityMapping   bool       `json:"identity_mapping,omitempty"`
}

type generatedMarker struct {
	Generator        string `json:"generator"`
	Authority        string `json:"authority"`
	RegistryVersion  int    `json:"registry_version"`
	MaterializedView string `json:"materialized_view_sha256"`
	Artifact         string `json:"artifact"`
}

type catalogManifest struct {
	ID                string `json:"id"`
	Availability      string `json:"availability"`
	Path              string `json:"path"`
	SHA256            string `json:"sha256"`
	RuntimeProjection string `json:"runtime_projection"`
}

type catalogFamily struct {
	ID                    string                  `json:"id"`
	EventName             observability.EventName `json:"event_name"`
	Signal                observability.Signal    `json:"signal"`
	Bucket                observability.Bucket    `json:"bucket"`
	CompatibilityProfiles []catalogFamilyProfile  `json:"compatibility_profiles"`
}

type catalogMembership struct {
	Profile  catalogFamilyProfile
	FamilyID string
	Bucket   observability.Bucket
}

type catalogFamilyProfile struct {
	ID                string `json:"id"`
	Availability      string `json:"availability"`
	Manifest          string `json:"manifest"`
	ManifestSHA256    string `json:"manifest_sha256"`
	RuntimeProjection string `json:"runtime_projection"`
}

type loadedProfile struct {
	raw      []byte
	manifest Manifest
	eligible map[string]struct{}
}

var cache struct {
	once     sync.Once
	profiles map[string]loadedProfile
	err      error
}

// Get returns a detached manifest snapshot. It fails closed if any generated
// profile or catalog binding is malformed or digest-inconsistent.
func Get(profileID string) (Manifest, error) {
	profiles, err := load()
	if err != nil {
		return Manifest{}, err
	}
	profile, ok := profiles[profileID]
	if !ok {
		return Manifest{}, fmt.Errorf("generated compatibility profile %q is unknown", profileID)
	}
	return decodeManifest(profile.raw)
}

// Eligible reports exact generated family membership. Invalid generated
// authority is indistinguishable from ineligibility at a projection boundary.
func Eligible(profileID string, signal observability.Signal, eventName observability.EventName) bool {
	profiles, err := load()
	if err != nil {
		return false
	}
	profile, ok := profiles[profileID]
	if !ok || profile.manifest.Availability != "available" || profile.manifest.RuntimeProjection.Status != "available" {
		return false
	}
	_, ok = profile.eligible[eligibilityKey(signal, eventName)]
	return ok
}

// Runtime returns a detached runtime-projection contract for implementations
// whose transformation is parameterized by generated profile facts.
func Runtime(profileID string) (RuntimeProjection, bool) {
	profiles, err := load()
	if err != nil {
		return RuntimeProjection{}, false
	}
	profile, ok := profiles[profileID]
	if !ok {
		return RuntimeProjection{}, false
	}
	result := profile.manifest.RuntimeProjection
	result.AttributeAliases = append([]AttributeAlias(nil), result.AttributeAliases...)
	result.EventAliasSources = append([]string(nil), result.EventAliasSources...)
	return result, true
}

// FamilyProjection returns a detached generated projection contract only when
// the profile is runtime-available and the family is eligible.
func FamilyProjection(
	profileID string,
	signal observability.Signal,
	eventName observability.EventName,
) (Projection, bool) {
	profiles, err := load()
	if err != nil {
		return Projection{}, false
	}
	profile, ok := profiles[profileID]
	if !ok || profile.manifest.Availability != "available" || profile.manifest.RuntimeProjection.Status != "available" {
		return Projection{}, false
	}
	for _, family := range profile.manifest.Families {
		if family.Signal != signal || family.EventName != eventName {
			continue
		}
		result := family.Projection
		if result.OperationAttribute != nil {
			operationAttribute := *result.OperationAttribute
			result.OperationAttribute = &operationAttribute
		}
		result.AllowedOperations = append([]string(nil), result.AllowedOperations...)
		result.AllowedSpanKinds = append([]string(nil), result.AllowedSpanKinds...)
		result.RequiredAttributes = append([]string(nil), result.RequiredAttributes...)
		result.Boundaries = append([]float64(nil), result.Boundaries...)
		result.LabelProjection.Mappings = cloneStringPairs(result.LabelProjection.Mappings)
		return result, true
	}
	return Projection{}, false
}

func load() (map[string]loadedProfile, error) {
	cache.once.Do(func() {
		cache.profiles, cache.err = loadProfiles()
	})
	return cache.profiles, cache.err
}

func loadProfiles() (map[string]loadedProfile, error) {
	var catalog struct {
		MaterializedView       string            `json:"materialized_view_sha256"`
		CompatibilityManifests []catalogManifest `json:"compatibility_manifests"`
		Families               []catalogFamily   `json:"families"`
	}
	if err := json.Unmarshal(publicschemas.TelemetryV8Catalog(), &catalog); err != nil {
		return nil, fmt.Errorf("decode generated telemetry catalog: %w", err)
	}
	if len(catalog.CompatibilityManifests) != 3 {
		return nil, fmt.Errorf("generated compatibility manifest inventory is incomplete")
	}
	expectedMembership := make(map[string]map[string]catalogMembership)
	for _, family := range catalog.Families {
		for _, profile := range family.CompatibilityProfiles {
			if expectedMembership[profile.ID] == nil {
				expectedMembership[profile.ID] = make(map[string]catalogMembership)
			}
			key := eligibilityKey(family.Signal, family.EventName)
			if _, duplicate := expectedMembership[profile.ID][key]; duplicate {
				return nil, fmt.Errorf("generated compatibility catalog repeats family membership")
			}
			expectedMembership[profile.ID][key] = catalogMembership{
				Profile: profile, FamilyID: family.ID, Bucket: family.Bucket,
			}
		}
	}
	profiles := make(map[string]loadedProfile, 3)
	for _, expected := range catalog.CompatibilityManifests {
		if expected.ID == "" ||
			(expected.Availability != "available" && expected.Availability != "pending") ||
			expected.Path != "compatibility/"+expected.ID+".json" {
			return nil, fmt.Errorf("generated compatibility catalog manifest metadata is invalid")
		}
		raw := publicschemas.TelemetryV8CompatibilityProfile(expected.ID)
		if len(raw) == 0 {
			return nil, fmt.Errorf("generated compatibility profile %q is not embedded", expected.ID)
		}
		digest := sha256.Sum256(raw)
		if hex.EncodeToString(digest[:]) != expected.SHA256 {
			return nil, fmt.Errorf("generated compatibility profile %q digest mismatch", expected.ID)
		}
		manifest, err := decodeManifest(raw)
		if err != nil {
			return nil, fmt.Errorf("decode generated compatibility profile %q: %w", expected.ID, err)
		}
		if err := validateManifest(manifest, expected, catalog.MaterializedView, expectedMembership[expected.ID]); err != nil {
			return nil, err
		}
		eligible := make(map[string]struct{}, len(manifest.Families))
		for _, family := range manifest.Families {
			eligible[eligibilityKey(family.Signal, family.EventName)] = struct{}{}
		}
		profiles[expected.ID] = loadedProfile{raw: append([]byte(nil), raw...), manifest: manifest, eligible: eligible}
	}
	return profiles, nil
}

func decodeManifest(raw []byte) (Manifest, error) {
	decoder := json.NewDecoder(bytes.NewReader(raw))
	decoder.DisallowUnknownFields()
	var manifest Manifest
	if err := decoder.Decode(&manifest); err != nil {
		return Manifest{}, err
	}
	var trailing any
	if err := decoder.Decode(&trailing); err != io.EOF {
		return Manifest{}, fmt.Errorf("compatibility profile has trailing JSON")
	}
	return manifest, nil
}

func validateManifest(
	manifest Manifest,
	expected catalogManifest,
	materializedView string,
	membership map[string]catalogMembership,
) error {
	if manifest.Format != manifestFormat || manifest.ProfileID != expected.ID || manifest.Availability != expected.Availability ||
		manifest.SchemaVersion != observability.CurrentRecordSchemaVersion ||
		manifest.BucketCatalogVersion != observability.CurrentBucketCatalogVersion || manifest.RegistryVersion < 1 ||
		manifest.MaterializedView != materializedView || manifest.Generated.MaterializedView != materializedView ||
		manifest.Generated.RegistryVersion != manifest.RegistryVersion || manifest.Generated.Artifact != expected.Path ||
		manifest.RuntimeProjection.Status != expected.RuntimeProjection || manifest.RuntimeProjection.UnsupportedBehavior != "reject" {
		return fmt.Errorf("generated compatibility profile %q metadata is invalid", expected.ID)
	}
	if len(manifest.Families) == 0 || len(manifest.Families) != len(membership) {
		return fmt.Errorf("generated compatibility profile %q membership is incomplete", expected.ID)
	}
	previous := ""
	seen := make(map[string]struct{}, len(manifest.Families))
	for _, family := range manifest.Families {
		key := eligibilityKey(family.Signal, family.EventName)
		orderKey := string(family.Signal) + "\x00" + family.FamilyID
		binding, ok := membership[key]
		if previous >= orderKey || !ok || family.Eligibility != "eligible" ||
			!observability.IsBucket(family.Bucket) || !observability.IsSignal(family.Signal) ||
			family.EventName.Validate() != nil || family.FamilyID != binding.FamilyID || family.Bucket != binding.Bucket ||
			binding.Profile.Availability != expected.Availability || binding.Profile.Manifest != expected.Path ||
			binding.Profile.ManifestSHA256 != expected.SHA256 ||
			binding.Profile.RuntimeProjection != expected.RuntimeProjection {
			return fmt.Errorf("generated compatibility profile %q family binding is invalid", expected.ID)
		}
		if _, duplicate := seen[key]; duplicate {
			return fmt.Errorf("generated compatibility profile %q repeats family membership", expected.ID)
		}
		seen[key] = struct{}{}
		previous = orderKey
		if err := validateProjection(manifest.ProfileID, family); err != nil {
			return err
		}
	}
	return nil
}

func validateProjection(profileID string, family Family) error {
	switch profileID {
	case "galileo-rich-v2":
		if family.Signal != observability.SignalTraces || family.Projection.Mode != "galileo_shape_v2" ||
			family.Projection.Shape == "" || family.Projection.OpenInferenceSpanKind == "" {
			return fmt.Errorf("generated Galileo family projection is invalid")
		}
	case "local-observability-v1":
		expectedMode := map[observability.Signal]string{
			observability.SignalLogs:    "canonical_otlp_log_v1",
			observability.SignalTraces:  "local_trace_aliases_v1",
			observability.SignalMetrics: "otel_sdk_metric_v1",
		}[family.Signal]
		if expectedMode == "" || family.Projection.Mode != expectedMode {
			return fmt.Errorf("generated local-observability family projection is invalid")
		}
		if family.Signal == observability.SignalMetrics && family.Projection.CardinalityLimit < 1 {
			return fmt.Errorf("generated local-observability metric cardinality limit is invalid")
		}
	case "openinference-v1":
		if family.Signal != observability.SignalTraces || family.Projection.Mode != "unsupported" ||
			family.Projection.Behavior != "reject" || family.Projection.Reason != "runtime_projector_not_implemented" {
			return fmt.Errorf("generated OpenInference unsupported projection is invalid")
		}
	default:
		return fmt.Errorf("generated compatibility profile %q is unknown", profileID)
	}
	return nil
}

func eligibilityKey(signal observability.Signal, eventName observability.EventName) string {
	return string(signal) + "\x00" + string(eventName)
}

func cloneStringPairs(input [][]string) [][]string {
	output := make([][]string, len(input))
	for index := range input {
		output[index] = append([]string(nil), input[index]...)
	}
	return output
}

// SortedFamilyIDs returns an immutable, deterministic inventory for focused
// converter conformance tests.
func SortedFamilyIDs(manifest Manifest, signal observability.Signal) []string {
	result := make([]string, 0, len(manifest.Families))
	for _, family := range manifest.Families {
		if family.Signal == signal {
			result = append(result, family.FamilyID)
		}
	}
	sort.Strings(result)
	return result
}
