#!/usr/bin/env python3
# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
"""Pure, fail-closed renderer for the telemetry-v8 generated Go candidate.

The renderer consumes only an in-memory ``CandidateRenderIndex`` and its
compiler-owned ``GoAPIPlanIR``.  It does not read registry YAML, reviewed
goldens, existing Go sources, or prior generated bytes.  This first foundation
renders the exact constant declaration inventory and the seven-file package
skeleton.  Compiler facts that are not yet syntax-complete are rejected before
any output object is constructed; incomplete family, structured, producer, or
fixture wrappers are never substituted with placeholders.

The returned objects are the exact input types accepted by
``telemetry_go_output_coordinator.preflight_go_outputs``.
"""

from __future__ import annotations

import dataclasses
import json
import re
from collections.abc import Mapping, Sequence
from typing import Any, Final

from telemetry_go_output_coordinator import (
    EXACT_GO_OUTPUT_PATHS,
    OUTPUT_MODE,
    OWNERSHIP_MARKER,
    GoDeclarationKey,
    GoFileDeclarationInventory,
    RenderedGoOutput,
    canonical_go_header,
)


class GoRenderError(RuntimeError):
    """The in-memory compiler contract cannot produce a complete candidate."""


@dataclasses.dataclass(frozen=True, slots=True)
class GoRenderCandidate:
    """One complete seven-file candidate plus its coordinator inventory."""

    outputs: tuple[RenderedGoOutput, ...]
    declaration_inventory: tuple[GoFileDeclarationInventory, ...]
    expected_declaration_keys: tuple[GoDeclarationKey, ...]
    materialized_view_sha256: str
    candidate_render_index_sha256: str
    go_symbol_table_sha256: str


_SHA256: Final = re.compile(r"^[0-9a-f]{64}$")
_GO_IDENTIFIER: Final = re.compile(r"^[A-Za-z][A-Za-z0-9]*$")
_EXPECTED_HEADERS: Final = (
    "materialized_view_sha256",
    "candidate_render_index_sha256",
    "go_symbol_table_sha256",
)
_MAX_DECLARATIONS: Final = 10_000
_MAX_PRIVATE_ROWS: Final = 100_000
_MAX_GO_STRING_BYTES: Final = 1_048_576


def _read(value: Any, name: str, path: str) -> Any:
    if dataclasses.is_dataclass(value) or hasattr(value, name):
        try:
            return getattr(value, name)
        except AttributeError:
            pass
    if isinstance(value, Mapping) and name in value:
        return value[name]
    raise GoRenderError(f"{path}: missing compiler fact {name}")


def _sequence(value: Any, path: str, *, maximum: int) -> tuple[Any, ...]:
    if not isinstance(value, Sequence) or isinstance(value, (str, bytes, bytearray)):
        raise GoRenderError(f"{path}: expected a bounded sequence")
    if len(value) > maximum:
        raise GoRenderError(f"{path}: sequence exceeds the renderer bound of {maximum}")
    return tuple(value)


def _string(value: Any, path: str) -> str:
    if not isinstance(value, str) or not value:
        raise GoRenderError(f"{path}: expected a nonempty string")
    return value


def _digest(value: Any, path: str) -> str:
    value = _string(value, path)
    if _SHA256.fullmatch(value) is None:
        raise GoRenderError(f"{path}: expected a canonical SHA-256 digest")
    return value


def _identifier(value: Any, path: str) -> str:
    value = _string(value, path)
    if _GO_IDENTIFIER.fullmatch(value) is None:
        raise GoRenderError(f"{path}: compiler supplied an invalid Go identifier")
    return value


def _go_string(value: Any, path: str) -> str:
    value = _string(value, path)
    if any(0xD800 <= ord(character) <= 0xDFFF for character in value):
        raise GoRenderError(f"{path}: Go string literal contains an unpaired surrogate")
    if len(value.encode("utf-8")) > _MAX_GO_STRING_BYTES:
        raise GoRenderError(f"{path}: Go string literal exceeds the renderer bound")
    # JSON and Go interpreted string literals share the escapes used here.  Keep
    # Unicode source text intact; there is no semantic normalization in rendering.
    return json.dumps(value, ensure_ascii=False)


def _type_name(type_ref: Any, path: str) -> str:
    arm = _string(_read(type_ref, "arm", path), f"{path}.arm")
    name = _read(type_ref, "name", path)
    element = _read(type_ref, "element", path)
    if arm in {"builtin", "named"}:
        if element is not None:
            raise GoRenderError(f"{path}: scalar Go type unexpectedly has an element")
        return _identifier(name, f"{path}.name")
    if arm in {"optional", "slice"}:
        if name is not None or element is None:
            raise GoRenderError(f"{path}: container Go type requires only an element")
        nested = _type_name(element, f"{path}.element")
        return f"Optional[{nested}]" if arm == "optional" else f"[]{nested}"
    raise GoRenderError(f"{path}: unsupported Go type AST arm {arm}")


def _constant_line(declaration: Any, position: int) -> str:
    path = f"GoAPIPlanIR.declarations[{position}]"
    if _read(declaration, "declaration_form", path) != "exported_const":
        raise GoRenderError(f"{path}: IDs file contains a non-constant declaration")
    symbol = _identifier(_read(declaration, "symbol", path), f"{path}.symbol")
    literal_kind = _read(declaration, "literal_kind", path)
    literal_value = _read(declaration, "literal_value", path)
    type_ref = _read(declaration, "go_type", path)
    if type_ref is None:
        raise GoRenderError(f"{path}: exported constant has no exact Go type")
    go_type = _type_name(type_ref, f"{path}.go_type")
    if literal_kind == "string":
        if go_type != "string" or not isinstance(literal_value, str):
            raise GoRenderError(f"{path}: string constant type/value disagree")
        literal = _go_string(literal_value, f"{path}.literal_value")
    elif literal_kind == "integer":
        if go_type != "int" or isinstance(literal_value, bool) or not isinstance(literal_value, int):
            raise GoRenderError(f"{path}: integer constant type/value disagree")
        # Preserve the compiler-selected exact Go type.  Keep generated
        # constants portable to every Go target rather than accepting a value
        # that compiles only where int happens to be 64 bits.
        if literal_value < -(2**31) or literal_value >= 2**31:
            raise GoRenderError(f"{path}: integer constant exceeds portable Go int")
        literal = str(literal_value)
    else:
        raise GoRenderError(f"{path}: unsupported exact constant literal kind")
    return f"\t{symbol} {go_type} = {literal}"


def _render_ids_body(declarations: tuple[Any, ...]) -> bytes:
    lines = ["package observability", ""]
    if declarations:
        lines.extend(
            ("const (", *(_constant_line(item, position) for position, item in enumerate(declarations)), ")", "")
        )
    return ("\n".join(lines) + "\n").encode("utf-8")


def _render_empty_body() -> bytes:
    return b"package observability\n"


def _declaration_key(declaration: Any, position: int) -> GoDeclarationKey:
    path = f"GoAPIPlanIR.declarations[{position}]"
    return GoDeclarationKey(
        _string(_read(declaration, "kind", path), f"{path}.kind"),
        _string(_read(declaration, "source_id", path), f"{path}.source_id"),
    )


def _validate_file_plans(plan: Any, declarations: tuple[Any, ...]) -> tuple[Any, ...]:
    files = _sequence(_read(plan, "files", "GoAPIPlanIR"), "GoAPIPlanIR.files", maximum=7)
    if len(files) != len(EXACT_GO_OUTPUT_PATHS):
        raise GoRenderError("GoAPIPlanIR.files: exact seven-file coverage is required")
    by_path: dict[str, Any] = {}
    declared_by_key = {_declaration_key(item, position): item for position, item in enumerate(declarations)}
    if len(declared_by_key) != len(declarations):
        raise GoRenderError("GoAPIPlanIR.declarations: duplicate declaration key")
    observed: list[GoDeclarationKey] = []
    for position, file_plan in enumerate(files):
        path = _string(_read(file_plan, "path", f"GoAPIPlanIR.files[{position}]"), "GoFilePlanIR.path")
        if path not in EXACT_GO_OUTPUT_PATHS or path in by_path:
            raise GoRenderError("GoAPIPlanIR.files: contains an extra or duplicate output path")
        headers = tuple(
            _sequence(
                _read(file_plan, "expected_digest_headers", f"GoFilePlanIR[{path}]"),
                f"GoFilePlanIR[{path}].expected_digest_headers",
                maximum=8,
            )
        )
        if headers != _EXPECTED_HEADERS:
            raise GoRenderError(f"GoFilePlanIR[{path}]: expected digest headers are not canonical")
        raw_keys = _sequence(
            _read(file_plan, "declaration_keys", f"GoFilePlanIR[{path}]"),
            f"GoFilePlanIR[{path}].declaration_keys",
            maximum=_MAX_DECLARATIONS,
        )
        keys: list[GoDeclarationKey] = []
        for key_position, key in enumerate(raw_keys):
            if not isinstance(key, Sequence) or isinstance(key, (str, bytes, bytearray)) or len(key) != 2:
                raise GoRenderError(f"GoFilePlanIR[{path}].declaration_keys[{key_position}]: invalid key")
            keys.append(GoDeclarationKey(_string(key[0], "declaration kind"), _string(key[1], "declaration source")))
        file_declarations = _sequence(
            _read(file_plan, "declarations", f"GoFilePlanIR[{path}]"),
            f"GoFilePlanIR[{path}].declarations",
            maximum=_MAX_DECLARATIONS,
        )
        file_keys = tuple(_declaration_key(item, key_position) for key_position, item in enumerate(file_declarations))
        if tuple(keys) != file_keys:
            raise GoRenderError(f"GoFilePlanIR[{path}]: declaration keys and declarations disagree")
        for key, declaration in zip(keys, file_declarations):
            if declared_by_key.get(key) is not declaration and declared_by_key.get(key) != declaration:
                raise GoRenderError(f"GoFilePlanIR[{path}]: declaration differs from the plan inventory")
            if _read(declaration, "output_file", f"declaration {key.kind}/{key.source_id}") != path:
                raise GoRenderError(f"declaration {key.kind}/{key.source_id}: output-file assignment disagrees")
        observed.extend(keys)
        by_path[path] = file_plan
    if set(by_path) != set(EXACT_GO_OUTPUT_PATHS):
        raise GoRenderError("GoAPIPlanIR.files: exact seven-file coverage is required")
    if (
        len(observed) != len(declarations)
        or len(set(observed)) != len(observed)
        or set(observed) != set(declared_by_key)
    ):
        raise GoRenderError("GoAPIPlanIR.files: declaration coverage is incomplete or duplicated")
    return tuple(by_path[path] for path in EXACT_GO_OUTPUT_PATHS)


def _missing_syntax_facts(index: Any, plan: Any, declarations: tuple[Any, ...]) -> tuple[str, ...]:
    """Return syntax-completion gaps without rendering any partial output."""

    missing: list[str] = []
    structured = _sequence(
        _read(plan, "structured", "GoAPIPlanIR"), "GoAPIPlanIR.structured", maximum=_MAX_DECLARATIONS
    )
    descriptors = _sequence(
        _read(plan, "descriptors", "GoAPIPlanIR"), "GoAPIPlanIR.descriptors", maximum=_MAX_DECLARATIONS
    )
    inputs = _sequence(_read(plan, "inputs", "GoAPIPlanIR"), "GoAPIPlanIR.inputs", maximum=_MAX_DECLARATIONS)
    callables = _sequence(_read(plan, "callables", "GoAPIPlanIR"), "GoAPIPlanIR.callables", maximum=_MAX_DECLARATIONS)
    producer_rows = _sequence(
        _read(index, "expanded_producer_mappings", "CandidateRenderIndex"),
        "CandidateRenderIndex.expanded_producer_mappings",
        maximum=_MAX_PRIVATE_ROWS,
    )
    examples = _sequence(
        _read(index, "examples", "CandidateRenderIndex"),
        "CandidateRenderIndex.examples",
        maximum=_MAX_PRIVATE_ROWS,
    )
    nonconstants = [
        item for item in declarations if _read(item, "declaration_form", "GoDeclarationPlanIR") != "exported_const"
    ]
    if descriptors:
        missing.append(
            "GoDescriptorPlanIR.kernel_contract_ast (complete field/constraint enums and trace limits, "
            "scope identity, schema/profile versions, and max event/link counts)"
        )
    if structured:
        missing.append(
            "GoStructuredPlanIR.arm_shape_and_conversion_ast (registered/dynamic/canonical arm storage, "
            "private marker, and exact recursive encoder operations)"
        )
    if inputs or callables or nonconstants:
        missing.append(
            "GoCallablePlanIR.body_ast (exact descriptor binding, typed value/condition conversion, "
            "mandatory resolution, and private-kernel invocation)"
        )
    if producer_rows:
        missing.append("GoProducerProjectionPlanIR (exact private row type, lookup API, and copy semantics)")
    if examples:
        missing.append(
            "GoFixturePlanIR (typed constructor inputs, normalized expected record bytes/classes, and stable failures)"
        )
    return tuple(missing)


def render_go_candidate(index: Any, plan: Any) -> GoRenderCandidate:
    """Render all seven in-memory outputs with one plan-bound inventory."""

    if _read(plan, "version", "GoAPIPlanIR") != 1:
        raise GoRenderError("GoAPIPlanIR.version: only version 1 is supported")
    materialized = _digest(
        _read(plan, "materialized_view_sha256", "GoAPIPlanIR"), "GoAPIPlanIR.materialized_view_sha256"
    )
    if (
        _digest(
            _read(index, "materialized_view_sha256", "CandidateRenderIndex"),
            "CandidateRenderIndex.materialized_view_sha256",
        )
        != materialized
    ):
        raise GoRenderError("CandidateRenderIndex and GoAPIPlanIR materialized-view digests disagree")
    candidate = _digest(
        _read(index, "candidate_render_index_sha256", "CandidateRenderIndex"),
        "CandidateRenderIndex.candidate_render_index_sha256",
    )
    symbol_table = _digest(_read(plan, "go_symbol_table_sha256", "GoAPIPlanIR"), "GoAPIPlanIR.go_symbol_table_sha256")
    declarations = _sequence(
        _read(plan, "declarations", "GoAPIPlanIR"),
        "GoAPIPlanIR.declarations",
        maximum=_MAX_DECLARATIONS,
    )
    files = _validate_file_plans(plan, declarations)
    missing = _missing_syntax_facts(index, plan, declarations)
    if missing:
        raise GoRenderError("complete seven-file Go render is blocked by missing compiler facts: " + "; ".join(missing))

    header = canonical_go_header(materialized, candidate, symbol_table)
    ids_path = EXACT_GO_OUTPUT_PATHS[0]
    outputs: list[RenderedGoOutput] = []
    inventories: list[GoFileDeclarationInventory] = []
    expected_keys: list[GoDeclarationKey] = []
    for file_plan, path in zip(files, EXACT_GO_OUTPUT_PATHS):
        file_declarations = _sequence(
            _read(file_plan, "declarations", f"GoFilePlanIR[{path}]"),
            f"GoFilePlanIR[{path}].declarations",
            maximum=_MAX_DECLARATIONS,
        )
        body = _render_ids_body(file_declarations) if path == ids_path else _render_empty_body()
        outputs.append(RenderedGoOutput(path, header + body, OWNERSHIP_MARKER, OUTPUT_MODE))
        keys = tuple(_declaration_key(item, position) for position, item in enumerate(file_declarations))
        inventories.append(GoFileDeclarationInventory(path, keys))
        expected_keys.extend(keys)
    return GoRenderCandidate(
        tuple(outputs),
        tuple(inventories),
        tuple(expected_keys),
        materialized,
        candidate,
        symbol_table,
    )


__all__ = ["GoRenderCandidate", "GoRenderError", "render_go_candidate"]
