#!/usr/bin/env python3
# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
"""Render candidate portable telemetry artifacts from one materialized view.

This module is deliberately downstream of the telemetry compiler.  Its only
semantic input is ``MaterializedRegistryView``; it never reads registry YAML,
constructs ``RegistryIR``, or consults current generated output.  Returned
artifacts are complete in-memory bytes and remain explicitly candidate authority
until a later cutover integrates them with the generated-output transaction.
"""

from __future__ import annotations

import base64
import dataclasses
import hashlib
import json
import math
import re
import unicodedata
from collections.abc import Mapping, Sequence
from pathlib import PurePosixPath
from types import MappingProxyType
from typing import Any, Final, TypeAlias


class CandidateRenderError(ValueError):
    """A content-free failure to render a complete candidate artifact set."""


@dataclasses.dataclass(frozen=True, slots=True)
class CandidateArtifact:
    """One deterministic repository-relative candidate output."""

    path: str
    payload: bytes
    media_type: str
    ownership_marker: bytes
    mode: int = 0o644


FrozenJSON: TypeAlias = None | bool | int | float | str | bytes | Mapping[str, "FrozenJSON"] | tuple["FrozenJSON", ...]
JSONObject: TypeAlias = dict[str, Any]

MATERIALIZED_VIEW_FORMAT: Final = "defenseclaw-materialized-registry-view-v1"
MATERIALIZED_VIEW_DIGEST_DOMAIN: Final = b"DefenseClaw MaterializedRegistryView v1\x00"
GENERATOR_ID: Final = "defenseclaw-telemetry-candidate-renderer-v1"
CANDIDATE_AUTHORITY: Final = "candidate-not-public-authority"
GENERATED_PREFIX: Final = "schemas/telemetry/generated"
JSON_OWNERSHIP_MARKER: Final = b'"x-defenseclaw-generated"'
MARKDOWN_MARKER_PREFIX: Final = "<!-- Code generated by DefenseClaw telemetry candidate renderer; DO NOT EDIT."
CANONICAL_JSON_DEFINITION: Final = "value:canonical_json"
_SHA256: Final = re.compile(r"^[0-9a-f]{64}$")
_EXAMPLE_PATH_SEGMENT: Final = re.compile(r"^[a-z][a-z0-9-]{0,127}$")


def _normalized_candidate_path(raw: str) -> str:
    """Validate and return one canonical repository-relative POSIX path."""

    if not isinstance(raw, str) or not raw or "\\" in raw or "\x00" in raw:
        raise CandidateRenderError("candidate output path is not canonical POSIX")
    if raw.startswith("/") or raw.endswith("/") or "//" in raw:
        raise CandidateRenderError("candidate output path is not canonical POSIX")
    path = PurePosixPath(raw)
    if path.is_absolute() or any(part in {"", ".", ".."} for part in path.parts):
        raise CandidateRenderError("candidate output path is not canonical POSIX")
    if path.as_posix() != raw:
        raise CandidateRenderError("candidate output path is not canonical POSIX")
    prefix = PurePosixPath(GENERATED_PREFIX).parts
    if path.parts[: len(prefix)] != prefix or len(path.parts) <= len(prefix):
        raise CandidateRenderError("candidate output path is outside the generated root")
    return path.as_posix()


def _candidate_path_identity(path: str) -> str:
    """Return the portable collision identity for a validated output path."""

    normalized = unicodedata.normalize("NFC", path)
    return unicodedata.normalize("NFC", normalized.casefold())


def _add_candidate_artifact(
    artifacts: dict[str, CandidateArtifact],
    artifact: CandidateArtifact,
) -> None:
    """Add one artifact after exact and portable collision checks."""

    path = _normalized_candidate_path(artifact.path)
    if path in artifacts:
        raise CandidateRenderError("candidate output path is duplicated")
    identity = _candidate_path_identity(path)
    if any(_candidate_path_identity(existing) == identity for existing in artifacts):
        raise CandidateRenderError("candidate output path has a portable collision")
    artifacts[path] = artifact


def _preflight_candidate_artifacts(
    artifacts: Mapping[str, CandidateArtifact],
) -> Mapping[str, CandidateArtifact]:
    """Validate the full output set before returning immutable candidates."""

    checked: dict[str, CandidateArtifact] = {}
    for key, artifact in artifacts.items():
        if not isinstance(artifact, CandidateArtifact) or artifact.path != key:
            raise CandidateRenderError("candidate artifact path does not match its key")
        _add_candidate_artifact(checked, artifact)
    return MappingProxyType({path: checked[path] for path in sorted(checked)})


_TOP_LEVEL_FIELDS: Final = frozenset(
    {
        "registry_path",
        "schema_version",
        "registry_version",
        "bucket_catalog_version",
        "imports",
        "dependency_lock_path",
        "examples_path",
        "input_digests",
        "dependencies",
        "semantic_profiles",
        "normalizers",
        "conditions",
        "mandatory_rule_catalog",
        "value_catalogs",
        "structural_contract",
        "metric_cardinality_limit",
        "metric_compatibility_profile",
        "domains",
        "group_resolution_order",
        "resolved_group_uses",
        "examples",
        "upstream_attribute_ownership",
        "legacy_only_upstream_attributes",
    }
)
_GROUP_FIELDS: Final = frozenset(
    {
        "id",
        "type",
        "brief",
        "stability",
        "extends",
        "attribute_uses",
        "attribute_refs",
        "resolved_uses",
        "event_refs",
        "event_name",
        "bucket",
        "span_name_pattern",
        "span_kinds",
        "span_status_rule",
        "instrument_name",
        "instrument_type",
        "metric_value_type",
        "metric_unit",
        "metric_description",
        "metric_temporality",
        "metric_boundaries",
        "empty_labels_reason",
        "metric_projections",
        "family_schema_version",
        "outcome_requirement",
        "allowed_outcomes",
        "link_relations",
        "mandatory_floor",
        "route_selector",
        "compatibility_profiles",
        "legacy_bindings",
        "introduced_in",
        "deprecated_in",
        "removed_in",
    }
)
_ATTRIBUTE_FIELDS: Final = frozenset(
    {
        "id",
        "field_type",
        "brief",
        "examples",
        "alias_of",
        "owner",
        "stability",
        "deprecated_in",
        "removed_in",
        "projection_only",
        "field_class",
        "sensitivity",
        "cardinality",
        "normalization",
        "introduced_in",
        "legacy_bindings",
    }
)
_ATTRIBUTE_EXTENSION_FIELDS: Final = frozenset({"ref", "field_class", "sensitivity", "cardinality", "normalization"})
_NORMALIZATION_FIELDS: Final = frozenset({"id", "overrides", "effective_constraints", "notes"})
_DOMAIN_FIELDS: Final = frozenset(
    {
        "domain",
        "path",
        "attributes",
        "attribute_extensions",
        "groups",
        "producer_identity_sets",
        "producer_mappings",
    }
)
_DEPENDENCY_FIELDS: Final = frozenset({"id", "repository", "version", "profile_id", "revision", "snapshot"})
_SNAPSHOT_FIELDS: Final = frozenset(
    {
        "format_version",
        "format",
        "dependency_id",
        "repository",
        "revision",
        "path",
        "sha256",
        "source_archive",
        "source_files",
        "attributes",
    }
)
_SNAPSHOT_ATTRIBUTE_FIELDS: Final = frozenset(
    {"id", "allowed_types", "shape", "stability", "stability_source", "source_pointer", "enum", "deprecated"}
)
_UPSTREAM_OWNERSHIP_FIELDS: Final = frozenset({"ref", "owner"})
_RESOLVED_USE_FIELDS: Final = frozenset({"ref", "role", "requirement_level", "conditional", "constraints", "origins"})
_EXAMPLE_FIELDS: Final = frozenset(
    {
        "id",
        "valid",
        "signal",
        "description",
        "family",
        "record",
        "expected_error",
        "field_classes",
        "base_example",
        "mutation",
        "builder_context",
    }
)
_STRUCTURAL_OBJECT_FIELDS: Final = frozenset({"id", "additional_properties", "fields"})
_STRUCTURAL_FIELD_FIELDS: Final = frozenset(
    {
        "name",
        "field_type",
        "required",
        "const_present",
        "const",
        "enum",
        "object_ref",
        "item_ref",
        "semantic_ref",
        "semantic_format",
        "field_class",
        "sensitivity",
        "normalization",
        "otlp_target",
        "otlp_encoding",
    }
)
_SIGNAL_ARM_FIELDS: Final = frozenset(
    {"signal", "payload_field", "required_fields", "forbidden_fields", "required_correlation_fields"}
)
_CANONICAL_OTLP_FIELDS: Final = frozenset(
    {
        "id",
        "json_mapping",
        "attribute_encoding",
        "any_value_encoding",
        "any_value_mapping",
        "null_value_policy",
        "object_contexts",
        "field_context_overrides",
        "timestamp_encoding",
        "id_encoding",
        "span_kind_mapping",
        "status_code_mapping",
        "signals",
    }
)
_CONDITION_FIELDS: Final = frozenset({"id", "description", "enforcement", "false_requirement"})
_MANDATORY_RULE_CATALOG_FIELDS: Final = frozenset({"version", "rules"})
_MANDATORY_RULE_FIELDS: Final = frozenset({"id", "enforcement"})
_MANDATORY_RULE_ENFORCEMENT_FIELDS: Final = frozenset({"kind", "value", "fact"})
_BUILDER_CONTEXT_FIELDS: Final = frozenset({"inheritance", "occurrence", "condition_facts", "mandatory_facts"})
_BUILDER_CONTEXT_INHERITANCE_FIELDS: Final = frozenset({"mode", "base_example"})
_BUILDER_OCCURRENCE_FIELDS: Final = frozenset({"timestamp", "record_id"})
_BUILDER_FACT_FIELDS: Final = frozenset({"fact", "value"})
_SEMANTIC_PROFILE_FIELDS: Final = frozenset(
    {
        "id",
        "trace_schema_version",
        "gen_ai_semconv_profile",
        "openinference_profile",
        "galileo_compatibility_profile",
    }
)
_VALUE_CATALOG_FIELDS: Final = frozenset(
    {"id", "kind", "value_attributes", "paired_value_attribute", "code_attribute", "entries", "compatibility"}
)
_COMPATIBILITY_PROFILES: Final = frozenset(
    {
        "galileo-rich-v2",
        "local-observability-v1",
        "openinference-v1",
    }
)
_FIELD_CLASSES: Final = (
    "metadata",
    "identifier",
    "content",
    "reason",
    "evidence",
    "error",
    "path",
    "credential",
)


def _canonical_json_number(text: str) -> str:
    if re.fullmatch(r"-?(?:0|[1-9][0-9]*)(?:\.[0-9]+)?(?:[eE][+-]?[0-9]+)?", text) is None:
        raise CandidateRenderError("materialized view contains an invalid number")
    negative = text.startswith("-")
    if negative:
        text = text[1:]
    exponent_text = "0"
    exponent_match = re.search(r"[eE]", text)
    if exponent_match is not None:
        exponent_text = text[exponent_match.start() + 1 :]
        text = text[: exponent_match.start()]
    integer_part, separator, fraction_part = text.partition(".")
    digits = (integer_part + (fraction_part if separator else "")).lstrip("0")
    if not digits:
        return "0"
    exponent = int(exponent_text) - len(fraction_part)
    trimmed = digits.rstrip("0")
    exponent += len(digits) - len(trimmed)
    digits = trimmed
    scientific_exponent = exponent + len(digits) - 1
    scientific = digits[0]
    if len(digits) > 1:
        scientific += "." + digits[1:]
    if scientific_exponent:
        scientific += f"e{scientific_exponent}"
    point = exponent + len(digits)
    if point <= 0:
        plain = "0." + ("0" * -point) + digits
    elif point >= len(digits):
        plain = digits + ("0" * (point - len(digits)))
    else:
        plain = digits[:point] + "." + digits[point:]
    result = plain if len(plain) <= len(scientific) else scientific
    return "-" + result if negative else result


def _canonical_json_string(value: str) -> str:
    result = ['"']
    escapes = {"\b": "\\b", "\t": "\\t", "\n": "\\n", "\f": "\\f", "\r": "\\r", '"': '\\"', "\\": "\\\\"}
    for character in value:
        codepoint = ord(character)
        if 0xD800 <= codepoint <= 0xDFFF:
            raise CandidateRenderError("materialized view contains an invalid string")
        if character in escapes:
            result.append(escapes[character])
        elif codepoint < 0x20:
            result.append(f"\\u{codepoint:04x}")
        else:
            result.append(character)
    result.append('"')
    return "".join(result)


def _canonical_json_text(value: Any) -> str:
    if value is None:
        return "null"
    if type(value) is bool:
        return "true" if value else "false"
    if type(value) is int:
        return _canonical_json_number(str(value))
    if type(value) is float:
        if not math.isfinite(value):
            raise CandidateRenderError("materialized view contains a non-finite number")
        return "0" if value == 0 else _canonical_json_number(repr(value))
    if isinstance(value, str):
        return _canonical_json_string(value)
    if isinstance(value, Mapping):
        if any(not isinstance(key, str) for key in value):
            raise CandidateRenderError("materialized view contains a non-string key")
        return (
            "{"
            + ",".join(_canonical_json_string(key) + ":" + _canonical_json_text(value[key]) for key in sorted(value))
            + "}"
        )
    if isinstance(value, (list, tuple)):
        return "[" + ",".join(_canonical_json_text(item) for item in value) + "]"
    raise CandidateRenderError("materialized view contains an unsupported value")


def _canonical_json_bytes(value: Any) -> bytes:
    return _canonical_json_text(value).encode("utf-8")


def _typed_materialized_node(value: FrozenJSON) -> FrozenJSON:
    if value is None:
        return ("null",)
    if type(value) is bool:
        return ("boolean", value)
    if type(value) is int:
        return ("int", str(value))
    if type(value) is float:
        return ("double", _canonical_json_number(repr(value)) if value != 0 else "0")
    if isinstance(value, bytes):
        return ("bytes", value.hex())
    if isinstance(value, str):
        return ("string", value)
    if isinstance(value, Mapping):
        if any(not isinstance(key, str) for key in value):
            raise CandidateRenderError("materialized view contains a non-string key")
        return ("object", tuple((key, _typed_materialized_node(value[key])) for key in sorted(value)))
    if isinstance(value, tuple):
        return ("array", tuple(_typed_materialized_node(item) for item in value))
    raise CandidateRenderError("materialized view contains a mutable or unsupported value")


def _plain(value: FrozenJSON) -> Any:
    if isinstance(value, Mapping):
        return {key: _plain(value[key]) for key in sorted(value)}
    if isinstance(value, tuple):
        return [_plain(item) for item in value]
    if isinstance(value, bytes):
        return {"$bytes": value.hex()}
    return value


def _plain_ir(value: FrozenJSON) -> Any:
    if isinstance(value, Mapping):
        if set(value) == {"$type", "fields"} and isinstance(value.get("$type"), str):
            fields = value.get("fields")
            if not isinstance(fields, Mapping):
                raise CandidateRenderError("materialized typed fields are invalid")
            return {key: _plain_ir(fields[key]) for key in sorted(fields)}
        return {key: _plain_ir(value[key]) for key in sorted(value)}
    if isinstance(value, tuple):
        return [_plain_ir(item) for item in value]
    if isinstance(value, bytes):
        return {"$bytes": value.hex()}
    return value


def _freeze(value: Any) -> Any:
    if isinstance(value, Mapping):
        return MappingProxyType({key: _freeze(value[key]) for key in sorted(value)})
    if isinstance(value, (list, tuple)):
        return tuple(_freeze(item) for item in value)
    if value is None or type(value) in {bool, int, float, str, bytes}:
        return value
    raise CandidateRenderError("candidate render index contains an unsupported value")


def _tagged(value: Any, type_name: str, expected_fields: frozenset[str] | None = None) -> Mapping[str, FrozenJSON]:
    if not isinstance(value, Mapping) or set(value) != {"$type", "fields"} or value["$type"] != type_name:
        raise CandidateRenderError(f"materialized view is missing {type_name}")
    fields = value["fields"]
    if not isinstance(fields, Mapping) or any(not isinstance(key, str) for key in fields):
        raise CandidateRenderError(f"materialized {type_name} fields are invalid")
    if expected_fields is not None and set(fields) != expected_fields:
        raise CandidateRenderError(f"materialized {type_name} fields are incomplete")
    return fields


def _resolved_use(value: Any) -> Mapping[str, FrozenJSON]:
    if isinstance(value, Mapping) and set(value) == _RESOLVED_USE_FIELDS:
        return value
    return _tagged(value, "ResolvedAttributeUseIR", _RESOLVED_USE_FIELDS)


def _string(value: Any, field: str) -> str:
    if not isinstance(value, str) or not value:
        raise CandidateRenderError(f"materialized {field} is invalid")
    return value


def _integer(value: Any, field: str, *, minimum: int = 0) -> int:
    if type(value) is not int or value < minimum:
        raise CandidateRenderError(f"materialized {field} is invalid")
    return value


def _deterministic_json_value(value: Any, *, root: bool = False) -> Any:
    if isinstance(value, Mapping):
        keys = sorted(value)
        if root and "x-defenseclaw-generated" in value:
            keys.remove("x-defenseclaw-generated")
            keys.insert(0, "x-defenseclaw-generated")
        return {key: _deterministic_json_value(value[key]) for key in keys}
    if isinstance(value, (list, tuple)):
        return [_deterministic_json_value(item) for item in value]
    return value


def _json_payload(value: Mapping[str, Any]) -> bytes:
    ordered = _deterministic_json_value(value, root=True)
    return (json.dumps(ordered, ensure_ascii=False, indent=2, sort_keys=False, allow_nan=False) + "\n").encode("utf-8")


def _authority_marker(*, registry_version: int, digest: str, artifact: str) -> JSONObject:
    return {
        "artifact": artifact,
        "authority": CANDIDATE_AUTHORITY,
        "generator": GENERATOR_ID,
        "materialized_view_sha256": digest,
        "registry_version": registry_version,
    }


def _candidate_conformance_scope() -> JSONObject:
    return {
        "scope": "canonical-schema-comparison-only",
        "builder_parity": "pending-source-inputs",
        "otlp_projection": "candidate",
        "required_materialized_inputs": [
            "builder_facts",
            "deterministic_occurrence_inputs",
        ],
        "non_json_schema_gates": [
            "builder_fact_conditions",
            "canonical_json_byte_depth_and_property_bounds",
            "complete_payload_leaf_field_class_coverage",
            "deterministic_record_and_occurrence_identity",
            "span_name_pattern_rendering",
            "trace_cross_field_derivation_equality",
            "trace_time_order_relation",
        ],
        "claim": "No generated-builder or producer parity is claimed by this candidate slice.",
    }


def _normalization(fields: Mapping[str, FrozenJSON]) -> JSONObject:
    node = _tagged(fields["normalization"], "NormalizationIR", _NORMALIZATION_FIELDS)
    effective = node.get("effective_constraints")
    overrides = node.get("overrides")
    if not isinstance(effective, Mapping) or not isinstance(overrides, Mapping):
        raise CandidateRenderError("materialized normalization is invalid")
    return {
        "id": _string(node.get("id"), "normalization id"),
        "overrides": _plain(overrides),
        "effective_constraints": _plain(effective),
        "notes": _plain(node.get("notes")),
    }


def _schema_type(field_type: str) -> JSONObject:
    if field_type in {"string", "timestamp"}:
        result: JSONObject = {"type": "string"}
        if field_type == "timestamp":
            result.update({"format": "date-time", "x-defenseclaw-format": "utc-rfc3339-nano"})
        return result
    if field_type == "boolean":
        return {"type": "boolean"}
    if field_type == "int64":
        return {"type": "integer", "minimum": -(2**63), "maximum": 2**63 - 1}
    if field_type == "uint32":
        return {"type": "integer", "minimum": 0, "maximum": 2**32 - 1}
    if field_type == "uint64":
        return {"type": "integer", "minimum": 0, "maximum": 2**64 - 1}
    if field_type == "double":
        return {"type": "number", "x-defenseclaw-finite": True}
    if field_type == "metric_number":
        return {"oneOf": [_schema_type("int64"), _schema_type("double")]}
    if field_type in {"string[]", "double[]", "int64[]", "boolean[]"}:
        item_type = field_type.removesuffix("[]")
        return {"type": "array", "items": _schema_type(item_type)}
    if field_type == "array":
        return {"type": "array"}
    if field_type == "object":
        return {"type": "object"}
    if field_type == "canonical_json":
        return {"$ref": f"#/$defs/{CANONICAL_JSON_DEFINITION}"}
    if field_type == "field_class_map":
        return {
            "type": "object",
            "propertyNames": {"pattern": r"^(?:/(?:[^~/]|~[01])*)+$"},
            "additionalProperties": {"enum": list(_FIELD_CLASSES)},
        }
    raise CandidateRenderError("materialized field type is unsupported")


def _canonical_json_schema() -> JSONObject:
    """Return the recursively closed canonical JSON value union.

    Canonical telemetry JSON deliberately excludes null because the canonical
    OTLP representation declares ``null_value_policy: reject``.  Array items
    and object values recurse through the same definition so null cannot be
    hidden below an otherwise valid container.
    """

    reference = {"$ref": f"#/$defs/{CANONICAL_JSON_DEFINITION}"}
    return {
        "oneOf": [
            {"type": "boolean"},
            {"type": "number", "x-defenseclaw-finite": True},
            {"type": "string"},
            {"type": "array", "items": reference},
            {"type": "object", "additionalProperties": reference},
        ],
        "x-defenseclaw-null-policy": "reject",
    }


def _apply_constraints(schema: JSONObject, constraints: Mapping[str, Any]) -> JSONObject:
    result = dict(schema)
    translations = {
        "enum": "enum",
        "pattern": "pattern",
        "min": "minimum",
        "max": "maximum",
        "min_items": "minItems",
        "max_items": "maxItems",
    }
    for key, target in translations.items():
        if key in constraints:
            result[target] = _plain(constraints[key])
    for key in ("max_utf8_bytes", "max_item_utf8_bytes", "max_depth", "max_properties"):
        if key in constraints:
            result[f"x-defenseclaw-{key.replace('_', '-')}"] = _plain(constraints[key])
    return result


@dataclasses.dataclass(frozen=True, slots=True)
class CandidateAttribute:
    id: str
    field_types: tuple[str, ...]
    metadata: Mapping[str, Any]


@dataclasses.dataclass(frozen=True, slots=True)
class CandidateDomain:
    """Immutable domain assignment and expanded producer contracts."""

    id: str
    path: str
    family_ids: tuple[str, ...]
    producer_identity_sets: tuple[Mapping[str, Any], ...]
    producer_mappings: tuple[Mapping[str, Any], ...]


@dataclasses.dataclass(frozen=True, slots=True)
class CandidateRenderIndex:
    """Recursively immutable, renderer-ready join of one materialized view."""

    schema_version: int
    registry_version: int
    bucket_catalog_version: int
    digest: str
    fields: Mapping[str, FrozenJSON]
    attributes: Mapping[str, CandidateAttribute]
    groups: Mapping[str, Mapping[str, FrozenJSON]]
    families: tuple[Mapping[str, FrozenJSON], ...]
    family_domains: Mapping[str, str]
    domains: tuple[CandidateDomain, ...]
    span_events: Mapping[str, Mapping[str, FrozenJSON]]
    examples: tuple[Mapping[str, FrozenJSON], ...]


def _validate_mandatory_rule_catalog(value: FrozenJSON) -> None:
    catalog = _tagged(value, "MandatoryRuleCatalogIR", _MANDATORY_RULE_CATALOG_FIELDS)
    if _integer(catalog["version"], "mandatory rule catalog version", minimum=1) != 1:
        raise CandidateRenderError("materialized mandatory rule catalog version is unsupported")
    rules = catalog["rules"]
    if not isinstance(rules, tuple) or not rules:
        raise CandidateRenderError("materialized mandatory rule catalog is incomplete")
    seen_ids: set[str] = set()
    seen_facts: set[str] = set()
    for raw_rule in rules:
        rule = _tagged(raw_rule, "MandatoryRuleIR", _MANDATORY_RULE_FIELDS)
        rule_id = _string(rule["id"], "mandatory rule id")
        if rule_id in seen_ids:
            raise CandidateRenderError("materialized mandatory rule ID is duplicated")
        enforcement = _tagged(
            rule["enforcement"],
            "MandatoryRuleEnforcementIR",
            _MANDATORY_RULE_ENFORCEMENT_FIELDS,
        )
        if enforcement["kind"] == "constant":
            if enforcement["value"] is not True or enforcement["fact"] is not None:
                raise CandidateRenderError("materialized constant mandatory rule is invalid")
        elif enforcement["kind"] == "builder_fact":
            fact = _string(enforcement["fact"], "mandatory builder fact")
            if enforcement["value"] is not None or fact in seen_facts:
                raise CandidateRenderError("materialized mandatory builder fact is invalid")
            seen_facts.add(fact)
        else:
            raise CandidateRenderError("materialized mandatory rule enforcement is invalid")
        seen_ids.add(rule_id)


def _validate_builder_context(example: Mapping[str, FrozenJSON]) -> None:
    context = _tagged(example["builder_context"], "BuilderContextIR", _BUILDER_CONTEXT_FIELDS)
    inheritance = _tagged(
        context["inheritance"],
        "BuilderContextInheritanceIR",
        _BUILDER_CONTEXT_INHERITANCE_FIELDS,
    )
    condition_facts = context["condition_facts"]
    mandatory_facts = context["mandatory_facts"]
    if not isinstance(condition_facts, tuple) or not isinstance(mandatory_facts, tuple):
        raise CandidateRenderError("materialized builder context facts are invalid")
    for facts in (condition_facts, mandatory_facts):
        seen: set[str] = set()
        for raw_fact in facts:
            fact = _tagged(raw_fact, "BuilderFactIR", _BUILDER_FACT_FIELDS)
            fact_name = _string(fact["fact"], "builder fact")
            if type(fact["value"]) is not bool or fact_name in seen:
                raise CandidateRenderError("materialized builder fact is invalid")
            seen.add(fact_name)

    if example["valid"] is True:
        if inheritance["mode"] != "explicit" or inheritance["base_example"] is not None:
            raise CandidateRenderError("materialized valid example builder inheritance is invalid")
        occurrence = _tagged(
            context["occurrence"],
            "BuilderOccurrenceIR",
            _BUILDER_OCCURRENCE_FIELDS,
        )
        if occurrence["timestamp"] != example["record"].get("timestamp") or occurrence["record_id"] != example[
            "record"
        ].get("record_id"):
            raise CandidateRenderError("materialized builder occurrence is inconsistent")
    elif (
        inheritance["mode"] != "exact_base"
        or inheritance["base_example"] != example["base_example"]
        or context["occurrence"] is not None
        or condition_facts
        or mandatory_facts
    ):
        raise CandidateRenderError("materialized invalid example builder inheritance is invalid")


def build_candidate_render_index(view: object) -> CandidateRenderIndex:
    if type(view).__name__ != "MaterializedRegistryView":
        raise CandidateRenderError("renderer requires MaterializedRegistryView")
    format_value = getattr(view, "format", None)
    digest = getattr(view, "typed_canonical_json_sha256", None)
    facts = getattr(view, "facts", None)
    if format_value != MATERIALIZED_VIEW_FORMAT or not isinstance(digest, str) or _SHA256.fullmatch(digest) is None:
        raise CandidateRenderError("materialized view identity is invalid")
    if not isinstance(facts, Mapping):
        raise CandidateRenderError("materialized view facts are invalid")
    observed_digest = hashlib.sha256(
        MATERIALIZED_VIEW_DIGEST_DOMAIN + _canonical_json_bytes(_typed_materialized_node(facts))
    ).hexdigest()
    if observed_digest != digest:
        raise CandidateRenderError("materialized view digest does not match facts")
    fields = _tagged(facts, "RegistryIR", _TOP_LEVEL_FIELDS)
    schema_version = _integer(fields["schema_version"], "schema version", minimum=1)
    registry_version = _integer(fields["registry_version"], "registry version", minimum=1)
    bucket_version = _integer(fields["bucket_catalog_version"], "bucket catalog version", minimum=1)
    _validate_mandatory_rule_catalog(fields["mandatory_rule_catalog"])

    ownership: dict[str, str] = {}
    for node in fields["upstream_attribute_ownership"]:
        item = _tagged(node, "UpstreamAttributeOwnershipIR", _UPSTREAM_OWNERSHIP_FIELDS)
        ref = _string(item.get("ref"), "upstream attribute ref")
        owner = _string(item.get("owner"), "upstream attribute owner")
        if ref in ownership:
            raise CandidateRenderError("materialized upstream attribute ownership is duplicated")
        ownership[ref] = owner

    snapshots: dict[str, dict[str, Mapping[str, FrozenJSON]]] = {}
    for node in fields["dependencies"]:
        dependency = _tagged(node, "DependencyIR", _DEPENDENCY_FIELDS)
        dependency_id = _string(dependency.get("id"), "dependency id")
        snapshot = _tagged(dependency.get("snapshot"), "SnapshotIR", _SNAPSHOT_FIELDS)
        for raw_attribute in snapshot.get("attributes", ()):
            attribute = _tagged(raw_attribute, "SnapshotAttribute", _SNAPSHOT_ATTRIBUTE_FIELDS)
            ref = _string(attribute.get("id"), "snapshot attribute id")
            by_dependency = snapshots.setdefault(ref, {})
            if dependency_id in by_dependency:
                raise CandidateRenderError("materialized snapshot attribute is duplicated")
            by_dependency[dependency_id] = attribute

    attributes: dict[str, CandidateAttribute] = {}
    groups: dict[str, Mapping[str, FrozenJSON]] = {}
    family_nodes: list[Mapping[str, FrozenJSON]] = []
    family_domains: dict[str, str] = {}
    domain_records: list[CandidateDomain] = []
    span_events: dict[str, Mapping[str, FrozenJSON]] = {}
    domains = fields["domains"]
    if not isinstance(domains, tuple) or not domains:
        raise CandidateRenderError("materialized domains are incomplete")
    for raw_domain in domains:
        domain = _tagged(raw_domain, "DomainIR", _DOMAIN_FIELDS)
        domain_id = _string(domain["domain"], "domain id")
        domain_path = _string(domain["path"], "domain path")
        domain_family_ids: list[str] = []
        for raw_attribute in domain.get("attributes", ()):
            item = _tagged(raw_attribute, "AttributeIR", _ATTRIBUTE_FIELDS)
            ref = _string(item["id"], "attribute id")
            if ref in attributes:
                raise CandidateRenderError("materialized attribute is duplicated")
            normalization = _normalization(item)
            metadata = {
                "id": ref,
                "type": item["field_type"],
                "brief": item["brief"],
                "examples": _plain(item["examples"]),
                "alias_of": item["alias_of"],
                "owner": item["owner"],
                "stability": item["stability"],
                "projection_only": item["projection_only"],
                "field_class": item["field_class"],
                "sensitivity": item["sensitivity"],
                "cardinality": item["cardinality"],
                "normalization": normalization,
                "introduced_in": item["introduced_in"],
                "deprecated_in": item["deprecated_in"],
                "removed_in": item["removed_in"],
            }
            attributes[ref] = CandidateAttribute(ref, (_string(item["field_type"], "attribute type"),), metadata)
        for raw_extension in domain.get("attribute_extensions", ()):
            extension = _tagged(raw_extension, "AttributeExtensionIR", _ATTRIBUTE_EXTENSION_FIELDS)
            ref = _string(extension["ref"], "attribute extension ref")
            if ref in attributes or ref not in snapshots or ref not in ownership:
                raise CandidateRenderError("materialized attribute extension is unresolved")
            dependency_for_owner = {
                "otel": "otel_core",
                "otel_genai": "otel_genai",
                "openinference_compatibility": "openinference",
            }
            dependency_id = dependency_for_owner.get(ownership[ref])
            snapshot = snapshots[ref].get(dependency_id or "")
            if snapshot is None:
                raise CandidateRenderError("materialized attribute extension has no owned snapshot")
            allowed_types = snapshot.get("allowed_types")
            if not isinstance(allowed_types, tuple) or any(not isinstance(v, str) for v in allowed_types):
                raise CandidateRenderError("materialized upstream attribute type is invalid")
            shape = snapshot.get("shape")
            if allowed_types:
                effective_types = allowed_types
            elif shape == "any_value":
                effective_types = ("canonical_json",)
            elif shape in {"indexed_prefix", "object_prefix"}:
                effective_types = ("object",)
            else:
                raise CandidateRenderError("materialized upstream attribute shape is invalid")
            normalization = _normalization(extension)
            metadata = {
                "id": ref,
                "type": list(effective_types) if len(effective_types) > 1 else effective_types[0],
                "upstream_shape": shape,
                "brief": "Pinned upstream semantic-convention attribute.",
                "examples": [],
                "alias_of": None,
                "owner": ownership[ref],
                "stability": snapshot["stability"],
                "projection_only": ownership[ref] == "openinference_compatibility",
                "field_class": extension["field_class"],
                "sensitivity": extension["sensitivity"],
                "cardinality": extension["cardinality"],
                "normalization": normalization,
                "introduced_in": None,
                "deprecated_in": None,
                "removed_in": None,
                "upstream_source": snapshot["source_pointer"],
            }
            attributes[ref] = CandidateAttribute(ref, tuple(effective_types), metadata)
        for raw_group in domain.get("groups", ()):
            group = _tagged(raw_group, "GroupIR", _GROUP_FIELDS)
            group_id = _string(group["id"], "group id")
            if group_id in groups:
                raise CandidateRenderError("materialized group is duplicated")
            groups[group_id] = group
            group_type = group["type"]
            if group_type in {"log", "span", "metric"}:
                family_nodes.append(group)
                domain_family_ids.append(group_id)
                family_domains[group_id] = domain_id
            elif group_type == "span_event":
                event_name_value = group["event_name"]
                event_name = (
                    _string(event_name_value, "span event name")
                    if event_name_value is not None
                    else group_id.removeprefix("event.")
                )
                if not event_name or event_name == group_id:
                    raise CandidateRenderError("materialized span event identity is invalid")
                if event_name in span_events:
                    raise CandidateRenderError("materialized span event is duplicated")
                span_events[event_name] = group
        producer_identity_sets = tuple(
            _freeze(_plain_ir(_tagged(item, "ProducerIdentitySetIR"))) for item in domain["producer_identity_sets"]
        )
        producer_mappings = tuple(
            _freeze(_plain_ir(_tagged(item, "ProducerMappingIR"))) for item in domain["producer_mappings"]
        )
        domain_records.append(
            CandidateDomain(
                domain_id,
                domain_path,
                tuple(sorted(domain_family_ids)),
                producer_identity_sets,
                producer_mappings,
            )
        )

    if set(fields["resolved_group_uses"]) != set(groups):
        raise CandidateRenderError("materialized resolved group uses are incomplete")
    for group_id, group in groups.items():
        resolved = fields["resolved_group_uses"][group_id]
        if resolved != group["resolved_uses"]:
            raise CandidateRenderError("materialized resolved group uses disagree")
        for raw_use in resolved:
            use = _resolved_use(raw_use)
            if use["ref"] not in attributes:
                raise CandidateRenderError("materialized resolved attribute use is unknown")

    active_identities: set[tuple[str, str]] = set()
    for family in family_nodes:
        group_type = family["type"]
        if family["removed_in"] is not None:
            continue
        identity = (
            {"log": "logs", "span": "traces", "metric": "metrics"}[group_type],
            _family_event_name(family),
        )
        if identity in active_identities:
            raise CandidateRenderError("materialized active family identity is duplicated")
        active_identities.add(identity)
        profiles = family["compatibility_profiles"] or ()
        if any(profile not in _COMPATIBILITY_PROFILES for profile in profiles):
            raise CandidateRenderError("materialized compatibility profile is unknown")

    examples: list[Mapping[str, FrozenJSON]] = []
    example_ids: set[str] = set()
    for raw_example in fields["examples"]:
        example = _tagged(raw_example, "ExampleIR", _EXAMPLE_FIELDS)
        example_id = _string(example["id"], "example id")
        if example_id in example_ids:
            raise CandidateRenderError("materialized example is duplicated")
        example_ids.add(example_id)
        if type(example["valid"]) is not bool or example["signal"] not in {"logs", "traces", "metrics"}:
            raise CandidateRenderError("materialized example metadata is invalid")
        family_id = example["family"]
        if family_id is not None and family_id not in groups:
            raise CandidateRenderError("materialized example family is unknown")
        if not isinstance(example["record"], Mapping) or example["record"].get("signal") != example["signal"]:
            raise CandidateRenderError("materialized example record is inconsistent")
        _validate_builder_context(example)
        examples.append(example)
    for example in examples:
        if example["valid"]:
            if (
                example["expected_error"] is not None
                or example["base_example"] is not None
                or example["mutation"] is not None
            ):
                raise CandidateRenderError("materialized valid example carries invalid metadata")
        else:
            if not isinstance(example["expected_error"], str) or example["base_example"] not in example_ids:
                raise CandidateRenderError("materialized invalid example is incomplete")
            _tagged(example["mutation"], "ExampleMutationIR")

    contract = _tagged(fields["structural_contract"], "StructuralContractIR")
    required_contract = {
        "id",
        "version",
        "additional_properties",
        "runtime_binding",
        "limits",
        "envelope",
        "correlation",
        "provenance",
        "signal_arms",
        "trace_derivations",
        "trace_body",
        "trace_relations",
        "trace_resource",
        "trace_scope",
        "trace_status",
        "trace_event",
        "trace_link",
        "metric_instrument_data",
        "canonical_to_otlp",
    }
    if set(contract) != required_contract:
        raise CandidateRenderError("materialized structural contract is incomplete")
    if tuple(_tagged(arm, "SignalArmIR", _SIGNAL_ARM_FIELDS)["signal"] for arm in contract["signal_arms"]) != (
        "logs",
        "traces",
        "metrics",
    ):
        raise CandidateRenderError("materialized signal arms are incomplete")

    frozen_attributes = MappingProxyType(
        {
            key: CandidateAttribute(
                attributes[key].id,
                attributes[key].field_types,
                _freeze(attributes[key].metadata),
            )
            for key in sorted(attributes)
        }
    )
    frozen_groups = MappingProxyType({key: _freeze(_plain_ir(groups[key])) for key in sorted(groups)})
    frozen_events = MappingProxyType({key: _freeze(_plain_ir(span_events[key])) for key in sorted(span_events)})
    return CandidateRenderIndex(
        schema_version=schema_version,
        registry_version=registry_version,
        bucket_catalog_version=bucket_version,
        digest=digest,
        fields=_freeze(fields),
        attributes=frozen_attributes,
        groups=frozen_groups,
        families=tuple(_freeze(_plain_ir(item)) for item in sorted(family_nodes, key=lambda item: item["id"])),
        family_domains=MappingProxyType({key: family_domains[key] for key in sorted(family_domains)}),
        domains=tuple(sorted(domain_records, key=lambda item: item.id)),
        span_events=frozen_events,
        examples=tuple(_freeze(item) for item in examples),
    )


def _family_event_name(family: Mapping[str, FrozenJSON]) -> str:
    if family["type"] == "log":
        return _string(family["event_name"], "log event name")
    if family["type"] == "span":
        return _string(family["id"], "span family id")
    if family["type"] == "metric":
        return _string(family["instrument_name"], "metric instrument name")
    raise CandidateRenderError("materialized family type is invalid")


def _attribute_schema(
    attribute: CandidateAttribute, use_constraints: Mapping[str, FrozenJSON] | None = None
) -> JSONObject:
    variants = [_schema_type(field_type) for field_type in attribute.field_types]
    schema = variants[0] if len(variants) == 1 else {"oneOf": variants}
    constraints = attribute.metadata["normalization"]["effective_constraints"]
    schema = _apply_constraints(schema, constraints)
    if use_constraints:
        schema = _apply_constraints(schema, use_constraints)
    schema["x-defenseclaw-field-class"] = attribute.metadata["field_class"]
    schema["x-defenseclaw-sensitivity"] = attribute.metadata["sensitivity"]
    schema["x-defenseclaw-owner"] = attribute.metadata["owner"]
    schema["x-defenseclaw-normalization"] = attribute.metadata["normalization"]
    return schema


def _phase_pair_rule(model: CandidateRenderIndex, properties: Mapping[str, Any]) -> JSONObject | None:
    if "defenseclaw.agent.phase" not in properties or "defenseclaw.agent.phase.code" not in properties:
        return None
    catalogs = model.fields["value_catalogs"]
    phase_catalog = None
    for raw in catalogs:
        item = _tagged(raw, "ValueCatalogIR", _VALUE_CATALOG_FIELDS)
        if item.get("id") == "agent-phase-v1":
            phase_catalog = item
            break
    if phase_catalog is None:
        raise CandidateRenderError("materialized agent phase catalog is missing")
    choices = []
    for raw_entry in phase_catalog["entries"]:
        entry = _tagged(raw_entry, "ValueCatalogEntryIR")
        choices.append(
            {
                "properties": {
                    "defenseclaw.agent.phase": {"const": entry["value"]},
                    "defenseclaw.agent.phase.code": {"const": entry["code"]},
                },
                "required": ["defenseclaw.agent.phase", "defenseclaw.agent.phase.code"],
            }
        )
    return {
        "if": {"required": ["defenseclaw.agent.phase", "defenseclaw.agent.phase.code"]},
        "then": {"oneOf": choices},
        "x-defenseclaw-value-catalog": "agent-phase-v1",
    }


def _uses_schema(
    model: CandidateRenderIndex,
    uses: Sequence[FrozenJSON],
    *,
    consts: Mapping[str, Any] | None = None,
) -> JSONObject:
    properties: JSONObject = {}
    required: list[str] = []
    for raw in uses:
        use = _resolved_use(raw)
        ref = _string(use["ref"], "resolved attribute ref")
        if ref in properties:
            raise CandidateRenderError("materialized resolved use is duplicated")
        constraints = use["constraints"]
        if not isinstance(constraints, Mapping):
            raise CandidateRenderError("materialized resolved constraints are invalid")
        schema = _attribute_schema(model.attributes[ref], constraints)
        if consts and ref in consts:
            schema["const"] = consts[ref]
        schema["x-defenseclaw-requirement-level"] = use["requirement_level"]
        if use["conditional"] is not None:
            schema["x-defenseclaw-condition"] = use["conditional"]
        properties[ref] = schema
        if use["requirement_level"] == "required":
            required.append(ref)
    result: JSONObject = {
        "type": "object",
        "additionalProperties": False,
        "properties": properties,
        "required": sorted(required),
    }
    phase_rule = _phase_pair_rule(model, properties)
    if phase_rule is not None:
        result["allOf"] = [phase_rule]
    return result


def _object_schema(
    model: CandidateRenderIndex, raw_object: FrozenJSON, definition_names: Mapping[str, str]
) -> JSONObject:
    obj = _tagged(raw_object, "StructuralObjectIR", _STRUCTURAL_OBJECT_FIELDS)
    object_id = _string(obj.get("id"), "structural object id")
    properties: JSONObject = {}
    required: list[str] = []
    for raw_field in obj.get("fields", ()):
        field = _tagged(raw_field, "StructuralFieldIR", _STRUCTURAL_FIELD_FIELDS)
        name = _string(field.get("name"), "structural field name")
        field_type = _string(field.get("field_type"), "structural field type")
        schema = _schema_type(field_type)
        object_ref = field.get("object_ref")
        item_ref = field.get("item_ref")
        if object_ref is not None:
            if object_ref not in definition_names:
                raise CandidateRenderError("materialized structural object reference is unknown")
            schema = {"$ref": f"#/$defs/{definition_names[object_ref]}"}
        elif item_ref is not None:
            if item_ref not in definition_names:
                raise CandidateRenderError("materialized structural item reference is unknown")
            schema = {"type": "array", "items": {"$ref": f"#/$defs/{definition_names[item_ref]}"}}
        if field.get("const_present") is True:
            schema["const"] = _plain(field.get("const"))
        enum = field.get("enum")
        if isinstance(enum, tuple) and enum:
            schema["enum"] = _plain(enum)
        normalization = field.get("normalization")
        if normalization is not None:
            norm = _tagged(normalization, "NormalizationIR", _NORMALIZATION_FIELDS)
            effective = norm.get("effective_constraints")
            if not isinstance(effective, Mapping):
                raise CandidateRenderError("materialized structural normalization is invalid")
            schema = _apply_constraints(schema, effective)
        for key in ("semantic_ref", "semantic_format", "field_class", "sensitivity", "otlp_target", "otlp_encoding"):
            if field.get(key) is not None:
                schema[f"x-defenseclaw-{key.replace('_', '-')}"] = _plain(field[key])
        properties[name] = schema
        if field.get("required") is True:
            required.append(name)
        elif field.get("required") is not False:
            raise CandidateRenderError("materialized structural required flag is invalid")
    return {
        "type": "object",
        "additionalProperties": bool(obj.get("additional_properties")),
        "properties": properties,
        "required": required,
        "x-defenseclaw-structural-object": object_id,
    }


def _event_definition(model: CandidateRenderIndex, event: Mapping[str, FrozenJSON], trace_event_def: str) -> JSONObject:
    event_name_value = event["event_name"]
    event_name = (
        _string(event_name_value, "span event name")
        if event_name_value is not None
        else _string(event["id"], "span event id").removeprefix("event.")
    )
    attributes = _uses_schema(model, event["resolved_uses"])
    return {
        "allOf": [
            {"$ref": f"#/$defs/{trace_event_def}"},
            {
                "type": "object",
                "properties": {"name": {"const": event_name}, "attributes": attributes},
                "required": ["name", "attributes"],
            },
        ],
        "x-defenseclaw-family-id": event["id"],
    }


def _family_definition(
    model: CandidateRenderIndex,
    family: Mapping[str, FrozenJSON],
    *,
    envelope_def: str,
    trace_defs: Mapping[str, str],
    event_defs: Mapping[str, str],
) -> JSONObject:
    family_id = _string(family["id"], "family id")
    family_type = family["type"]
    signal = {"log": "logs", "span": "traces", "metric": "metrics"}.get(family_type)
    if signal is None:
        raise CandidateRenderError("materialized family type is invalid")
    bucket = _string(family["bucket"], "family bucket")
    event_name = _family_event_name(family)
    overlay_properties: JSONObject = {
        "signal": {"const": signal},
        "bucket": {"const": bucket},
        "event_name": {"const": event_name},
    }
    required = ["signal", "bucket", "event_name"]
    uses = family["resolved_uses"]
    if not isinstance(uses, tuple):
        raise CandidateRenderError("materialized family resolved uses are invalid")

    if family_type == "log":
        body_uses = tuple(raw for raw in uses if _resolved_use(raw)["role"] == "body_fields")
        overlay_properties["body"] = _uses_schema(model, body_uses)
        required.append("body")
    elif family_type == "span":
        consts = {
            "defenseclaw.bucket": bucket,
            "defenseclaw.span.family": family_id,
            "defenseclaw.span.family_schema_version": family["family_schema_version"],
        }
        attributes = _uses_schema(model, uses, consts=consts)
        body_properties: JSONObject = {"attributes": attributes}
        kinds = family["span_kinds"]
        if not isinstance(kinds, tuple) or not kinds:
            raise CandidateRenderError("materialized span kinds are incomplete")
        body_properties["kind"] = {"enum": list(kinds)}
        resource_group = model.groups.get("resource.core")
        scope_group = model.groups.get("scope.core")
        link_group = model.groups.get("link.core")
        if resource_group is None or scope_group is None or link_group is None:
            raise CandidateRenderError("materialized trace support groups are incomplete")
        body_properties["resource"] = {
            "allOf": [
                {"$ref": f"#/$defs/{trace_defs['trace_resource']}"},
                {"properties": {"attributes": _uses_schema(model, resource_group["resolved_uses"])}},
            ]
        }
        body_properties["scope"] = {
            "allOf": [
                {"$ref": f"#/$defs/{trace_defs['trace_scope']}"},
                {"properties": {"attributes": _uses_schema(model, scope_group["resolved_uses"])}},
            ]
        }
        allowed_events = family["event_refs"] or ()
        if any(event not in event_defs for event in allowed_events):
            raise CandidateRenderError("materialized span event reference is unknown")
        if allowed_events:
            body_properties["events"] = {
                "type": "array",
                "items": {"oneOf": [{"$ref": f"#/$defs/{event_defs[event]}"} for event in allowed_events]},
            }
        body_overlay: JSONObject = {"type": "object", "properties": body_properties}
        if not allowed_events:
            body_overlay["not"] = {"required": ["events"]}
        link_attributes = _uses_schema(model, link_group["resolved_uses"])
        relations = family["link_relations"] or ()
        if "defenseclaw.link.relation" in link_attributes["properties"] and relations:
            link_attributes["properties"]["defenseclaw.link.relation"]["enum"] = list(relations)
        body_properties["links"] = {
            "type": "array",
            "items": {
                "allOf": [
                    {"$ref": f"#/$defs/{trace_defs['trace_link']}"},
                    {"properties": {"attributes": link_attributes}},
                ]
            },
        }
        overlay_properties["body"] = {
            "allOf": [
                {"$ref": f"#/$defs/{trace_defs['trace_body']}"},
                body_overlay,
            ]
        }
        required.extend(["body", "span_name"])
    else:
        labels = _uses_schema(model, uses)
        value_type = _string(family["metric_value_type"], "metric value type")
        overlay_properties["instrument_data"] = {
            "allOf": [
                {"$ref": f"#/$defs/{trace_defs['metric_instrument_data']}"},
                {"properties": {"value": _schema_type(value_type), "attributes": labels}},
            ]
        }
        required.append("instrument_data")

    outcome_requirement = family["outcome_requirement"]
    allowed_outcomes = family["allowed_outcomes"]
    overlay: JSONObject = {
        "type": "object",
        "properties": overlay_properties,
        "required": sorted(set(required)),
    }
    if family_type != "metric":
        if outcome_requirement not in {"required", "optional", "forbidden"} or not isinstance(allowed_outcomes, tuple):
            raise CandidateRenderError("materialized family outcome contract is incomplete")
        if outcome_requirement == "forbidden":
            overlay.setdefault("allOf", []).append({"not": {"required": ["outcome"]}})
        else:
            overlay_properties["outcome"] = {"enum": list(allowed_outcomes)}
            if outcome_requirement == "required":
                overlay["required"].append("outcome")

    return {
        "allOf": [{"$ref": f"#/$defs/{envelope_def}"}, overlay],
        "title": family_id,
        "description": family["brief"],
        "x-defenseclaw-family": {
            "id": family_id,
            "signal": signal,
            "bucket": bucket,
            "event_name": event_name,
            "family_schema_version": family["family_schema_version"],
            "span_name_pattern": family["span_name_pattern"],
            "status_rule": family["span_status_rule"],
            "conditions": sorted(
                {_resolved_use(raw)["conditional"] for raw in uses if _resolved_use(raw)["conditional"] is not None}
            ),
        },
    }


def _render_schema(model: CandidateRenderIndex, marker: JSONObject) -> JSONObject:
    contract = _tagged(model.fields["structural_contract"], "StructuralContractIR")
    structural_keys = (
        "envelope",
        "correlation",
        "provenance",
        "trace_body",
        "trace_resource",
        "trace_scope",
        "trace_status",
        "trace_event",
        "trace_link",
        "metric_instrument_data",
    )
    structural_nodes = {
        key: _tagged(contract[key], "StructuralObjectIR", _STRUCTURAL_OBJECT_FIELDS) for key in structural_keys
    }
    definition_names = {node["id"]: f"structural:{key}" for key, node in structural_nodes.items()}
    defs: JSONObject = {CANONICAL_JSON_DEFINITION: _canonical_json_schema()}
    for key, raw in structural_nodes.items():
        defs[f"structural:{key}"] = _object_schema(model, contract[key], definition_names)

    envelope_def = "structural:envelope"
    envelope = defs[envelope_def]
    signal_rules: list[JSONObject] = []
    for raw_arm in contract["signal_arms"]:
        arm = _tagged(raw_arm, "SignalArmIR", _SIGNAL_ARM_FIELDS)
        then: JSONObject = {"required": list(arm["required_fields"]) + [arm["payload_field"]]}
        forbidden = list(arm["forbidden_fields"])
        if forbidden:
            then["allOf"] = [{"not": {"required": [field]}} for field in forbidden]
        correlation_required = list(arm["required_correlation_fields"])
        if correlation_required:
            then.setdefault("properties", {})["correlation"] = {"required": correlation_required}
        signal_rules.append({"if": {"properties": {"signal": {"const": arm["signal"]}}}, "then": then})
    envelope["allOf"] = signal_rules

    for ref, attribute in sorted(model.attributes.items()):
        defs[f"attribute:{ref}"] = _attribute_schema(attribute)

    event_defs: dict[str, str] = {}
    for event_name, event in sorted(model.span_events.items()):
        name = f"event:{event_name}"
        defs[name] = _event_definition(model, event, "structural:trace_event")
        event_defs[event_name] = name

    active_refs: list[JSONObject] = []
    for family in model.families:
        if family["removed_in"] is not None:
            continue
        family_id = _string(family["id"], "family id")
        name = f"family:{family_id}"
        defs[name] = _family_definition(
            model,
            family,
            envelope_def=envelope_def,
            trace_defs={key: f"structural:{key}" for key in structural_keys},
            event_defs=event_defs,
        )
        active_refs.append({"$ref": f"#/$defs/{name}"})
    if not active_refs:
        raise CandidateRenderError("materialized view has no active families")

    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://defenseclaw.dev/schemas/telemetry/v8/telemetry.schema.json",
        "title": "DefenseClaw Portable Telemetry Candidate Bundle",
        "description": "Candidate-only schema generated from one immutable MaterializedRegistryView.",
        "x-defenseclaw-generated": marker,
        "x-defenseclaw-versions": {
            "schema_version": model.schema_version,
            "registry_version": model.registry_version,
            "bucket_catalog_version": model.bucket_catalog_version,
            "materialized_view_sha256": model.digest,
        },
        "x-defenseclaw-conformance": _candidate_conformance_scope(),
        "x-defenseclaw-conditions": [
            _plain_ir(_tagged(item, "ConditionIR", _CONDITION_FIELDS)) for item in model.fields["conditions"]
        ],
        "x-defenseclaw-mandatory-rule-catalog": _plain_ir(
            _tagged(
                model.fields["mandatory_rule_catalog"],
                "MandatoryRuleCatalogIR",
                _MANDATORY_RULE_CATALOG_FIELDS,
            )
        ),
        "x-defenseclaw-value-catalogs": [
            _plain_ir(_tagged(item, "ValueCatalogIR", _VALUE_CATALOG_FIELDS)) for item in model.fields["value_catalogs"]
        ],
        "x-defenseclaw-trace-derivations": [
            _plain_ir(_tagged(item, "TraceDerivationIR")) for item in contract["trace_derivations"]
        ],
        "x-defenseclaw-trace-relations": [
            _plain_ir(_tagged(item, "StructuralRelationIR")) for item in contract["trace_relations"]
        ],
        "x-defenseclaw-canonical-to-otlp": _plain_ir(
            _tagged(contract["canonical_to_otlp"], "CanonicalOTLPRepresentationIR", _CANONICAL_OTLP_FIELDS)
        ),
        "oneOf": active_refs,
        "$defs": {key: defs[key] for key in sorted(defs)},
    }


def _family_catalog_entry(model: CandidateRenderIndex, family: Mapping[str, FrozenJSON]) -> JSONObject:
    family_id = _string(family["id"], "family id")
    signal = {"log": "logs", "span": "traces", "metric": "metrics"}[family["type"]]
    uses = []
    for raw in family["resolved_uses"]:
        use = _resolved_use(raw)
        attribute = model.attributes[use["ref"]]
        uses.append(
            {
                "ref": use["ref"],
                "role": use["role"],
                "requirement_level": use["requirement_level"],
                "condition": use["conditional"],
                "constraints": _plain(use["constraints"]),
                "type": attribute.metadata["type"],
                "owner": attribute.metadata["owner"],
                "field_class": attribute.metadata["field_class"],
                "sensitivity": attribute.metadata["sensitivity"],
                "cardinality": attribute.metadata["cardinality"],
                "stability": attribute.metadata["stability"],
            }
        )
    profiles = list(family["compatibility_profiles"] or ())
    return {
        "id": family_id,
        "signal": signal,
        "bucket": family["bucket"],
        "event_name": _family_event_name(family),
        "kind": family["type"],
        "brief": family["brief"],
        "stability": family["stability"],
        "route_selector": family["route_selector"],
        "family_schema_version": family["family_schema_version"],
        "span": {
            "name_pattern": family["span_name_pattern"],
            "kinds": _plain(family["span_kinds"]),
            "status_rule": family["span_status_rule"],
        }
        if family["type"] == "span"
        else None,
        "metric": {
            "instrument_name": family["instrument_name"],
            "instrument_type": family["instrument_type"],
            "value_type": family["metric_value_type"],
            "unit": family["metric_unit"],
            "temporality": family["metric_temporality"],
            "boundaries": _plain(family["metric_boundaries"]),
            "cardinality_limit": model.fields["metric_cardinality_limit"],
        }
        if family["type"] == "metric"
        else None,
        "outcome": {
            "requirement": family["outcome_requirement"],
            "allowed": _plain(family["allowed_outcomes"]),
        }
        if family["type"] != "metric"
        else None,
        "fields": sorted(uses, key=lambda item: (item["role"], item["ref"])),
        "required_attributes": sorted(item["ref"] for item in uses if item["requirement_level"] == "required"),
        "conditional_attributes": sorted(item["ref"] for item in uses if item["requirement_level"] == "conditional"),
        "optional_attributes": sorted(
            item["ref"] for item in uses if item["requirement_level"] in {"recommended", "optional"}
        ),
        "allowed_events": _plain(family["event_refs"]),
        "allowed_link_relations": _plain(family["link_relations"]),
        "mandatory_floor": _plain(family["mandatory_floor"]),
        "compatibility_profiles": [
            {"id": profile, "availability": "pending", "manifest": None} for profile in profiles
        ],
        "lifecycle": {
            "introduced_in": family["introduced_in"],
            "deprecated_in": family["deprecated_in"],
            "removed_in": family["removed_in"],
        },
    }


def _render_catalog(model: CandidateRenderIndex, marker: JSONObject) -> JSONObject:
    contract = _tagged(model.fields["structural_contract"], "StructuralContractIR")
    return {
        "x-defenseclaw-generated": marker,
        "format": "defenseclaw-telemetry-catalog-v1",
        "schema_version": model.schema_version,
        "registry_version": model.registry_version,
        "bucket_catalog_version": model.bucket_catalog_version,
        "materialized_view_sha256": model.digest,
        "conformance": _candidate_conformance_scope(),
        "structural_contract": {
            "id": contract["id"],
            "version": contract["version"],
            "signal_arms": [
                _plain_ir(_tagged(item, "SignalArmIR", _SIGNAL_ARM_FIELDS)) for item in contract["signal_arms"]
            ],
            "trace_derivations": [
                _plain_ir(_tagged(item, "TraceDerivationIR")) for item in contract["trace_derivations"]
            ],
            "trace_relations": [
                _plain_ir(_tagged(item, "StructuralRelationIR")) for item in contract["trace_relations"]
            ],
            "canonical_to_otlp": _plain_ir(
                _tagged(contract["canonical_to_otlp"], "CanonicalOTLPRepresentationIR", _CANONICAL_OTLP_FIELDS)
            ),
        },
        "semantic_profiles": [
            _plain_ir(_tagged(item, "SemanticProfileIR", _SEMANTIC_PROFILE_FIELDS))
            for item in model.fields["semantic_profiles"]
        ],
        "conditions": [
            _plain_ir(_tagged(item, "ConditionIR", _CONDITION_FIELDS)) for item in model.fields["conditions"]
        ],
        "mandatory_rule_catalog": _plain_ir(
            _tagged(
                model.fields["mandatory_rule_catalog"],
                "MandatoryRuleCatalogIR",
                _MANDATORY_RULE_CATALOG_FIELDS,
            )
        ),
        "value_catalogs": [
            _plain_ir(_tagged(item, "ValueCatalogIR", _VALUE_CATALOG_FIELDS)) for item in model.fields["value_catalogs"]
        ],
        "attributes": [dict(model.attributes[key].metadata) for key in sorted(model.attributes)],
        "families": [_family_catalog_entry(model, family) for family in model.families],
        "compatibility_manifests": [
            {"id": profile, "availability": "pending", "path": None} for profile in sorted(_COMPATIBILITY_PROFILES)
        ],
    }


def _render_catalog_markdown(model: CandidateRenderIndex, catalog: Mapping[str, Any], marker: JSONObject) -> bytes:
    generated_header = (
        f"{MARKDOWN_MARKER_PREFIX} authority={CANDIDATE_AUTHORITY}; "
        f"registry={model.registry_version}; view={model.digest}; -->"
    )
    lines = [
        generated_header,
        "",
        "# DefenseClaw Portable Telemetry Catalog (Candidate)",
        "",
        "> This generated candidate is not yet public schema authority.",
        "",
        "## Namespace decision",
        "",
        "Portable protocol and GenAI meaning uses `http.*`, `rpc.*`, `error.*`, `db.*`, and `gen_ai.*`. "
        "DefenseClaw security, policy, lifecycle, provenance, correlation, privacy, and routing meaning uses "
        "`defenseclaw.*`. OpenInference and Galileo names are compatibility projections, never producer-canonical.",
        "",
        "## Trace tree examples",
        "",
    ]
    valid_traces = [example for example in model.examples if example["valid"] and example["signal"] == "traces"]
    for example in valid_traces:
        record = example["record"]
        correlation = record.get("correlation", {})
        lines.append(
            f"- `{example['family']}` — `{record.get('span_name')}`; trace `{correlation.get('trace_id')}`, "
            f"span `{correlation.get('span_id')}`."
        )
    lines.extend(
        [
            "",
            "## Backend compatibility",
            "",
            "| Profile | Candidate status |",
            "|---|---|",
        ]
    )
    for profile in sorted(_COMPATIBILITY_PROFILES):
        lines.append(f"| `{profile}` | pending; no candidate path is claimed |")
    lines.extend(
        [
            "",
            "## Families",
            "",
            "| Family | Signal | Bucket | Event/instrument | Required | Privacy-sensitive fields | Lifecycle |",
            "|---|---|---|---|---:|---:|---|",
        ]
    )
    for family in catalog["families"]:
        sensitive = sum(1 for field in family["fields"] if field["sensitivity"] != "safe")
        lifecycle = family["lifecycle"]
        state = "removed" if lifecycle["removed_in"] else "deprecated" if lifecycle["deprecated_in"] else "active"
        lines.append(
            f"| `{family['id']}` | `{family['signal']}` | `{family['bucket']}` | `{family['event_name']}` | "
            f"{len(family['required_attributes'])} | {sensitive} | {state} |"
        )
    lines.extend(
        [
            "",
            "## Query guidance",
            "",
            "Start with portable fields such as `gen_ai.operation.name`, `gen_ai.provider.name`, "
            "`service.name`, and `error.type`; add `defenseclaw.bucket`, `defenseclaw.span.family`, "
            "and typed policy/security fields only for DefenseClaw-specific questions.",
            "",
            "## Redaction",
            "",
            "Every catalog field carries `field_class` and `sensitivity`. Route redaction operates on those "
            "generated classifications before any compatibility projection.",
            "",
            "## Conformance scope",
            "",
            "This slice proves canonical JSON Schema comparison and candidate OTLP projection only. "
            "Generated-builder parity remains pending until the materialized example contract carries "
            "builder facts and deterministic occurrence inputs. Span-name rendering, cross-field trace "
            "equalities/time order, exact payload-leaf field-class coverage, and canonical JSON byte/depth "
            "bounds remain explicit non-JSON-Schema gates.",
            "",
        ]
    )
    del marker
    return "\n".join(lines).encode("utf-8")


def _normalized_mutation(value: FrozenJSON | None) -> JSONObject | None:
    if value is None:
        return None
    mutation = _tagged(value, "ExampleMutationIR")
    changes = []
    for raw in mutation.get("changes", ()):
        change = _tagged(raw, "ExampleMutationChangeIR")
        item = {"op": change["op"], "path": change["path"]}
        if change["value_present"]:
            item["value"] = _plain(change["value"])
        changes.append(item)
    return {"kind": mutation["kind"], "changes": changes}


def _example_document(model: CandidateRenderIndex, example: Mapping[str, FrozenJSON], marker: JSONObject) -> JSONObject:
    return {
        "x-defenseclaw-generated": marker,
        "schema_version": model.schema_version,
        "registry_version": model.registry_version,
        "materialized_view_sha256": model.digest,
        "conformance": _candidate_conformance_scope(),
        "id": example["id"],
        "valid": example["valid"],
        "signal": example["signal"],
        "family": example["family"],
        "description": example["description"],
        "expected_error": example["expected_error"],
        "base_example": example["base_example"],
        "mutation": _normalized_mutation(example["mutation"]),
        "builder_context": _plain_ir(example["builder_context"]),
        "field_classes": _plain(example["field_classes"]),
        "record": _plain(example["record"]),
    }


def _any_value(value: Any) -> JSONObject:
    if value is None:
        raise CandidateRenderError("canonical null cannot be projected to OTLP AnyValue")
    if type(value) is bool:
        return {"boolValue": value}
    if type(value) is int:
        return {"intValue": str(value)}
    if type(value) is float:
        if not math.isfinite(value):
            raise CandidateRenderError("non-finite value cannot be projected to OTLP")
        return {"doubleValue": value}
    if isinstance(value, str):
        return {"stringValue": value}
    if isinstance(value, list):
        return {"arrayValue": {"values": [_any_value(item) for item in value]}}
    if isinstance(value, Mapping):
        return {"kvlistValue": {"values": _key_values(value)}}
    raise CandidateRenderError("canonical value cannot be projected to OTLP")


def _key_values(attributes: Mapping[str, Any]) -> list[JSONObject]:
    return [{"key": key, "value": _any_value(attributes[key])} for key in sorted(attributes)]


def _otlp_bytes_id(value: Any, *, octets: int, field: str) -> str:
    if not isinstance(value, str) or re.fullmatch(rf"[0-9a-f]{{{octets * 2}}}", value) is None:
        raise CandidateRenderError(f"canonical {field} is not a lowercase hexadecimal identifier")
    raw = bytes.fromhex(value)
    if not any(raw):
        raise CandidateRenderError(f"canonical {field} cannot be all zero")
    return base64.b64encode(raw).decode("ascii")


def _trace_otlp(record: Mapping[str, Any], contract: Mapping[str, FrozenJSON]) -> JSONObject:
    body = record["body"]
    correlation = record["correlation"]
    if not isinstance(body, Mapping) or not isinstance(correlation, Mapping):
        raise CandidateRenderError("trace example has invalid canonical structure")
    representation = _tagged(contract["canonical_to_otlp"], "CanonicalOTLPRepresentationIR", _CANONICAL_OTLP_FIELDS)
    kind_map = dict(representation["span_kind_mapping"])
    status_map = dict(representation["status_code_mapping"])
    status = body["status"]
    resource = body["resource"]
    scope = body["scope"]
    span: JSONObject = {
        "traceId": _otlp_bytes_id(correlation["trace_id"], octets=16, field="trace_id"),
        "spanId": _otlp_bytes_id(correlation["span_id"], octets=8, field="span_id"),
        "name": record["span_name"],
        "kind": kind_map[body["kind"]],
        "startTimeUnixNano": str(body["start_time_unix_nano"]),
        "endTimeUnixNano": str(body["end_time_unix_nano"]),
        "attributes": _key_values(body["attributes"]),
        "status": {"code": status_map[status["code"]]},
    }
    direct_fields = {
        "parent_span_id": "parentSpanId",
        "dropped_attributes_count": "droppedAttributesCount",
        "dropped_events_count": "droppedEventsCount",
        "dropped_links_count": "droppedLinksCount",
    }
    for source, target in direct_fields.items():
        if source in body:
            span[target] = (
                _otlp_bytes_id(body[source], octets=8, field="parent_span_id")
                if source == "parent_span_id"
                else body[source]
            )
    if "description" in status:
        span["status"]["message"] = status["description"]
    if "events" in body:
        span["events"] = [
            {
                "name": event["name"],
                "timeUnixNano": str(event["time_unix_nano"]),
                "attributes": _key_values(event["attributes"]),
                **(
                    {"droppedAttributesCount": event["dropped_attributes_count"]}
                    if "dropped_attributes_count" in event
                    else {}
                ),
            }
            for event in body["events"]
        ]
    if "links" in body:
        span["links"] = [
            {
                "traceId": _otlp_bytes_id(link["trace_id"], octets=16, field="link trace_id"),
                "spanId": _otlp_bytes_id(link["span_id"], octets=8, field="link span_id"),
                "attributes": _key_values(link["attributes"]),
                **({"traceState": link["trace_state"]} if "trace_state" in link else {}),
                **(
                    {"droppedAttributesCount": link["dropped_attributes_count"]}
                    if "dropped_attributes_count" in link
                    else {}
                ),
            }
            for link in body["links"]
        ]
    resource_message: JSONObject = {"attributes": _key_values(resource["attributes"])}
    if "dropped_attributes_count" in resource:
        resource_message["droppedAttributesCount"] = resource["dropped_attributes_count"]
    scope_message: JSONObject = {
        "name": scope["name"],
        "version": scope["version"],
        "attributes": _key_values(scope["attributes"]),
    }
    if "dropped_attributes_count" in scope:
        scope_message["droppedAttributesCount"] = scope["dropped_attributes_count"]
    return {
        "resourceSpans": [
            {
                "resource": resource_message,
                "schemaUrl": resource["schema_url"],
                "scopeSpans": [
                    {
                        "scope": scope_message,
                        "schemaUrl": scope["schema_url"],
                        "spans": [span],
                    }
                ],
            }
        ]
    }


def _otlp_expectation(model: CandidateRenderIndex, example: Mapping[str, FrozenJSON]) -> JSONObject:
    record = _plain(example["record"])
    contract = _tagged(model.fields["structural_contract"], "StructuralContractIR")
    representation = _tagged(contract["canonical_to_otlp"], "CanonicalOTLPRepresentationIR", _CANONICAL_OTLP_FIELDS)
    signal = example["signal"]
    if signal == "traces":
        return {"mode": "direct_span", "request": _trace_otlp(record, contract)}
    if signal == "logs":
        return {
            "mode": "projected_record_json_string",
            "request_root": "resourceLogs",
            "projected_record_json": _canonical_json_bytes(record).decode("utf-8"),
        }
    family = model.groups.get(example["family"])
    if family is None:
        raise CandidateRenderError("metric fixture family is missing")
    return {
        "mode": "sdk_aggregation_required",
        "request_root": "resourceMetrics",
        "instrument": {
            "name": family["instrument_name"],
            "type": family["instrument_type"],
            "value_type": family["metric_value_type"],
            "unit": family["metric_unit"],
            "temporality": family["metric_temporality"],
            "boundaries": _plain(family["metric_boundaries"]),
            "value": record["instrument_data"]["value"],
            "attributes": record["instrument_data"]["attributes"],
        },
        "canonical_to_otlp": {
            "representation_id": representation["id"],
            "attribute_encoding": representation["attribute_encoding"],
            "any_value_encoding": representation["any_value_encoding"],
        },
    }


def _preflight_example_output_ids(examples: Sequence[Mapping[str, FrozenJSON]]) -> None:
    """Validate example IDs and all paths derived from them before rendering."""

    planned: dict[str, CandidateArtifact] = {}
    for example in examples:
        example_id = example.get("id")
        if not isinstance(example_id, str) or _EXAMPLE_PATH_SEGMENT.fullmatch(example_id) is None:
            raise CandidateRenderError("example id is not a portable output path segment")
        category = "valid" if example.get("valid") is True else "invalid"
        for relative in (
            f"examples/{category}/{example_id}.json",
            f"otlp-fixtures/cases/{example_id}.json",
        ):
            path = f"{GENERATED_PREFIX}/{relative}"
            _add_candidate_artifact(
                planned,
                CandidateArtifact(path, b"preflight", "application/json", JSON_OWNERSHIP_MARKER),
            )


def render_candidate_artifacts(view: object) -> Mapping[str, CandidateArtifact]:
    """Return the complete immutable candidate artifact set for ``view``.

    Paths are repository-relative and directly consumable by the generated-output
    transaction adapter.  This function performs no filesystem I/O.
    """

    model = build_candidate_render_index(view)
    _preflight_example_output_ids(model.examples)
    artifacts: dict[str, CandidateArtifact] = {}

    def add_json(relative: str, document: JSONObject) -> None:
        path = f"{GENERATED_PREFIX}/{relative}"
        _add_candidate_artifact(
            artifacts,
            CandidateArtifact(path, _json_payload(document), "application/json", JSON_OWNERSHIP_MARKER),
        )

    schema_marker = _authority_marker(
        registry_version=model.registry_version,
        digest=model.digest,
        artifact="telemetry.schema.json",
    )
    schema = _render_schema(model, schema_marker)
    add_json("telemetry.schema.json", schema)

    catalog_marker = _authority_marker(
        registry_version=model.registry_version, digest=model.digest, artifact="catalog.json"
    )
    catalog = _render_catalog(model, catalog_marker)
    add_json("catalog.json", catalog)
    markdown_path = f"{GENERATED_PREFIX}/catalog.md"
    _add_candidate_artifact(
        artifacts,
        CandidateArtifact(
            markdown_path,
            _render_catalog_markdown(model, catalog, catalog_marker),
            "text/markdown; charset=utf-8",
            MARKDOWN_MARKER_PREFIX.encode("ascii"),
        ),
    )

    example_entries: list[JSONObject] = []
    otlp_entries: list[JSONObject] = []
    for example in model.examples:
        category = "valid" if example["valid"] else "invalid"
        relative = f"examples/{category}/{example['id']}.json"
        marker = _authority_marker(registry_version=model.registry_version, digest=model.digest, artifact=relative)
        add_json(relative, _example_document(model, example, marker))
        example_entries.append(
            {
                "id": example["id"],
                "valid": example["valid"],
                "signal": example["signal"],
                "family": example["family"],
                "path": relative,
                "expected_error": example["expected_error"],
            }
        )
        fixture_relative = f"otlp-fixtures/cases/{example['id']}.json"
        fixture_marker = _authority_marker(
            registry_version=model.registry_version,
            digest=model.digest,
            artifact=fixture_relative,
        )
        expectation = (
            {"accepted": True, "projection": _otlp_expectation(model, example)}
            if example["valid"]
            else {"accepted": False, "error_code": example["expected_error"]}
        )
        add_json(
            fixture_relative,
            {
                "x-defenseclaw-generated": fixture_marker,
                "fixture_format": "defenseclaw-otlp-fixture-v1",
                "materialized_view_sha256": model.digest,
                "conformance": _candidate_conformance_scope(),
                "id": example["id"],
                "signal": example["signal"],
                "family": example["family"],
                "canonical_record": _plain(example["record"]),
                "expect": expectation,
            },
        )
        otlp_entries.append(
            {
                "id": example["id"],
                "signal": example["signal"],
                "family": example["family"],
                "valid": example["valid"],
                "expected_error": example["expected_error"],
                "path": fixture_relative,
            }
        )

    examples_marker = _authority_marker(
        registry_version=model.registry_version,
        digest=model.digest,
        artifact="examples/manifest.json",
    )
    add_json(
        "examples/manifest.json",
        {
            "x-defenseclaw-generated": examples_marker,
            "format": "defenseclaw-normalized-examples-v1",
            "materialized_view_sha256": model.digest,
            "conformance": _candidate_conformance_scope(),
            "cases": example_entries,
        },
    )
    otlp_marker = _authority_marker(
        registry_version=model.registry_version,
        digest=model.digest,
        artifact="otlp-fixtures/manifest.json",
    )
    contract = _tagged(model.fields["structural_contract"], "StructuralContractIR")
    add_json(
        "otlp-fixtures/manifest.json",
        {
            "x-defenseclaw-generated": otlp_marker,
            "format": "defenseclaw-otlp-fixture-manifest-v1",
            "materialized_view_sha256": model.digest,
            "conformance": _candidate_conformance_scope(),
            "canonical_to_otlp": _plain_ir(
                _tagged(contract["canonical_to_otlp"], "CanonicalOTLPRepresentationIR", _CANONICAL_OTLP_FIELDS)
            ),
            "cases": otlp_entries,
        },
    )
    return _preflight_candidate_artifacts(artifacts)


__all__ = [
    "CANDIDATE_AUTHORITY",
    "CandidateArtifact",
    "CandidateAttribute",
    "CandidateDomain",
    "CandidateRenderIndex",
    "CandidateRenderError",
    "build_candidate_render_index",
    "render_candidate_artifacts",
]
